"""Raw UniFFI-generated bindings — private implementation detail.

Do not import from this subpackage in application code; use the public API
re-exported from :mod:`bkndb` instead. This module's shape tracks
``crates/bkndb-ffi``'s Rust surface directly and can change between
releases without a deprecation cycle.

Regenerated by ``scripts/build_native.py`` — never hand-edit `bkndb_ffi.py`
or the compiled library alongside it.
"""
