# This file was autogenerated by some hot garbage in the `uniffi` crate.
# Trust me, you don't want to mess with it!

# Common helper code.
#
# Ideally this would live in a separate .py file where it can be unittested etc
# in isolation, and perhaps even published as a re-useable package.
#
# However, it's important that the details of how this helper code works (e.g. the
# way that different builtin types are passed across the FFI) exactly match what's
# expected by the rust code on the other side of the interface. In practice right
# now that means coming from the exact some version of `uniffi` that was used to
# compile the rust component. The easiest way to ensure this is to bundle the Python
# helpers directly inline like we're doing here.

from __future__ import annotations
import os
import sys
import ctypes
from dataclasses import dataclass
import enum
import struct
import contextlib
import datetime
import threading
import itertools
import traceback
import typing
import platform


# Used for default argument values
_DEFAULT = object() # type: typing.Any

import ctypes
import struct

class _UniffiRustBuffer(ctypes.Structure):
    _fields_ = [
        ("capacity", ctypes.c_uint64),
        ("len", ctypes.c_uint64),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    @staticmethod
    def default():
        return _UniffiRustBuffer(0, 0, None)

    @staticmethod
    def alloc(size):
        return _uniffi_rust_call(_UniffiLib.ffi_bkndb_ffi_rustbuffer_alloc, size)

    @staticmethod
    def reserve(rbuf, additional):
        return _uniffi_rust_call(_UniffiLib.ffi_bkndb_ffi_rustbuffer_reserve, rbuf, additional)

    def free(self):
        return _uniffi_rust_call(_UniffiLib.ffi_bkndb_ffi_rustbuffer_free, self)

    def __str__(self):
        return "_UniffiRustBuffer(capacity={}, len={}, data={})".format(
            self.capacity,
            self.len,
            self.data[0:self.len]
        )

    @contextlib.contextmanager
    def alloc_with_builder(*args):
        """Context-manger to allocate a buffer using a _UniffiRustBufferBuilder.

        The allocated buffer will be automatically freed if an error occurs, ensuring that
        we don't accidentally leak it.
        """
        builder = _UniffiRustBufferBuilder()
        try:
            yield builder
        except:
            builder.discard()
            raise

    @contextlib.contextmanager
    def consume_with_stream(self):
        """Context-manager to consume a buffer using a _UniffiRustBufferStream.

        The _UniffiRustBuffer will be freed once the context-manager exits, ensuring that we don't
        leak it even if an error occurs.
        """
        try:
            s = _UniffiRustBufferStream.from_rust_buffer(self)
            yield s
            if s.remaining() != 0:
                raise RuntimeError(f"junk data left in buffer at end of consume_with_stream {s.remaining()}")
        finally:
            self.free()

    @contextlib.contextmanager
    def read_with_stream(self):
        """Context-manager to read a buffer using a _UniffiRustBufferStream.

        This is like consume_with_stream, but doesn't free the buffer afterwards.
        It should only be used with borrowed `_UniffiRustBuffer` data.
        """
        s = _UniffiRustBufferStream.from_rust_buffer(self)
        yield s
        if s.remaining() != 0:
            raise RuntimeError(f"junk data left in buffer at end of read_with_stream {s.remaining()}")

class _UniffiForeignBytes(ctypes.Structure):
    _fields_ = [
        ("len", ctypes.c_int32),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    def __str__(self):
        return "_UniffiForeignBytes(len={}, data={})".format(self.len, self.data[0:self.len])


class _UniffiFfiConverterByRefBytes:
    """Zero-copy converter for `&[u8]` / `[ByRef] bytes` arguments.

    Only `lower` and `check_lower` are valid — zero-copy byte buffers only
    flow foreign -> Rust, and only in argument position. `lift`, `read`, and
    `write` have no sound implementation here.

    CPython `bytes` objects are immutable and their internal buffer doesn't
    move for the lifetime of the object; the caller must keep the source
    `bytes` alive for the duration of the FFI call.
    """

    @staticmethod
    def check_lower(value):
        # Tighter than `bytes-like`: `lower` uses `ctypes.c_char_p` which only
        # accepts `bytes`/`None`, so fail fast with a matching check.
        if not isinstance(value, bytes):
            raise TypeError("a bytes object is required, not {!r}".format(type(value).__name__))

    @staticmethod
    def lower(value):
        fb = _UniffiForeignBytes()
        if len(value) == 0:
            fb.len = 0
            fb.data = None
        else:
            fb.len = len(value)
            fb.data = ctypes.cast(ctypes.c_char_p(value), ctypes.POINTER(ctypes.c_char))
        return fb

    @staticmethod
    def lift(value):
        raise NotImplementedError("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")

    @staticmethod
    def read(buf):
        raise NotImplementedError("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")

    @staticmethod
    def write(value, buf):
        raise NotImplementedError("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")


class _UniffiRustBufferStream:
    """
    Helper for structured reading of bytes from a _UniffiRustBuffer
    """

    def __init__(self, data, len):
        self.data = data
        self.len = len
        self.offset = 0

    @classmethod
    def from_rust_buffer(cls, buf):
        return cls(buf.data, buf.len)

    def remaining(self):
        return self.len - self.offset

    def _unpack_from(self, size, format):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        value = struct.unpack(format, self.data[self.offset:self.offset+size])[0]
        self.offset += size
        return value

    def read(self, size):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        data = self.data[self.offset:self.offset+size]
        self.offset += size
        return data

    def read_i8(self):
        return self._unpack_from(1, ">b")

    def read_u8(self):
        return self._unpack_from(1, ">B")

    def read_i16(self):
        return self._unpack_from(2, ">h")

    def read_u16(self):
        return self._unpack_from(2, ">H")

    def read_i32(self):
        return self._unpack_from(4, ">i")

    def read_u32(self):
        return self._unpack_from(4, ">I")

    def read_i64(self):
        return self._unpack_from(8, ">q")

    def read_u64(self):
        return self._unpack_from(8, ">Q")

    def read_float(self):
        v = self._unpack_from(4, ">f")
        return v

    def read_double(self):
        return self._unpack_from(8, ">d")

class _UniffiRustBufferBuilder:
    """
    Helper for structured writing of bytes into a _UniffiRustBuffer.
    """

    def __init__(self):
        self.rbuf = _UniffiRustBuffer.alloc(16)
        self.rbuf.len = 0

    def finalize(self):
        rbuf = self.rbuf
        self.rbuf = None
        return rbuf

    def discard(self):
        if self.rbuf is not None:
            rbuf = self.finalize()
            rbuf.free()

    @contextlib.contextmanager
    def _reserve(self, num_bytes):
        if self.rbuf.len + num_bytes > self.rbuf.capacity:
            self.rbuf = _UniffiRustBuffer.reserve(self.rbuf, num_bytes)
        yield None
        self.rbuf.len += num_bytes

    def _pack_into(self, size, format, value):
        with self._reserve(size):
            packed = struct.pack(format, value)
            if size > 0:
                ctypes.memmove(ctypes.addressof(self.rbuf.data.contents) + self.rbuf.len, packed, size)
    
    def write(self, value):
        length = len(value)
        with self._reserve(length):
            if length > 0:
                ctypes.memmove(ctypes.addressof(self.rbuf.data.contents) + self.rbuf.len, value, length)

    def write_i8(self, v):
        self._pack_into(1, ">b", v)

    def write_u8(self, v):
        self._pack_into(1, ">B", v)

    def write_i16(self, v):
        self._pack_into(2, ">h", v)

    def write_u16(self, v):
        self._pack_into(2, ">H", v)

    def write_i32(self, v):
        self._pack_into(4, ">i", v)

    def write_u32(self, v):
        self._pack_into(4, ">I", v)

    def write_i64(self, v):
        self._pack_into(8, ">q", v)

    def write_u64(self, v):
        self._pack_into(8, ">Q", v)

    def write_float(self, v):
        self._pack_into(4, ">f", v)

    def write_double(self, v):
        self._pack_into(8, ">d", v)

    def write_c_size_t(self, v):
        self._pack_into(ctypes.sizeof(ctypes.c_size_t) , "@N", v)
# A handful of classes and functions to support the generated data structures.
# This would be a good candidate for isolating in its own ffi-support lib.

class InternalError(Exception):
    pass

class _UniffiRustCallStatus(ctypes.Structure):
    """
    Error runtime.
    """
    _fields_ = [
        ("code", ctypes.c_int8),
        ("error_buf", _UniffiRustBuffer),
    ]

    # These match the values from the uniffi::rustcalls module
    CALL_SUCCESS = 0
    CALL_ERROR = 1
    CALL_UNEXPECTED_ERROR = 2

    @staticmethod
    def default():
        return _UniffiRustCallStatus(code=_UniffiRustCallStatus.CALL_SUCCESS, error_buf=_UniffiRustBuffer.default())

    def __str__(self):
        if self.code == _UniffiRustCallStatus.CALL_SUCCESS:
            return "_UniffiRustCallStatus(CALL_SUCCESS)"
        elif self.code == _UniffiRustCallStatus.CALL_ERROR:
            return "_UniffiRustCallStatus(CALL_ERROR)"
        elif self.code == _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR:
            return "_UniffiRustCallStatus(CALL_UNEXPECTED_ERROR)"
        else:
            return "_UniffiRustCallStatus(<invalid code>)"

def _uniffi_rust_call(fn, *args):
    # Call a rust function
    return _uniffi_rust_call_with_error(None, fn, *args)

def _uniffi_rust_call_with_error(error_ffi_converter, fn, *args):
    # Call a rust function and handle any errors
    #
    # This function is used for rust calls that return Result<> and therefore can set the CALL_ERROR status code.
    # error_ffi_converter must be set to the _UniffiConverter for the error class that corresponds to the result.
    call_status = _UniffiRustCallStatus.default()

    args_with_error = args + (ctypes.byref(call_status),)
    result = fn(*args_with_error)
    _uniffi_check_call_status(error_ffi_converter, call_status)
    return result

def _uniffi_check_call_status(error_ffi_converter, call_status):
    if call_status.code == _UniffiRustCallStatus.CALL_SUCCESS:
        pass
    elif call_status.code == _UniffiRustCallStatus.CALL_ERROR:
        if error_ffi_converter is None:
            call_status.error_buf.free()
            raise InternalError("_uniffi_rust_call_with_error: CALL_ERROR, but error_ffi_converter is None")
        else:
            raise error_ffi_converter.lift(call_status.error_buf)
    elif call_status.code == _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR:
        # When the rust code sees a panic, it tries to construct a _UniffiRustBuffer
        # with the message.  But if that code panics, then it just sends back
        # an empty buffer.
        if call_status.error_buf.len > 0:
            msg = _UniffiFfiConverterString.lift(call_status.error_buf)
        else:
            msg = "Unknown rust panic"
        raise InternalError(msg)
    else:
        raise InternalError("Invalid _UniffiRustCallStatus code: {}".format(
            call_status.code))

def _uniffi_trait_interface_call(call_status, make_call, write_return_value):
    try:
        return write_return_value(make_call())
    except Exception as e:
        call_status.code = _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR
        call_status.error_buf = _UniffiFfiConverterString.lower(repr(e))

def _uniffi_trait_interface_call_with_error(call_status, make_call, write_return_value, error_type, lower_error):
    try:
        try:
            return write_return_value(make_call())
        except error_type as e:
            call_status.code = _UniffiRustCallStatus.CALL_ERROR
            call_status.error_buf = lower_error(e)
    except Exception as e:
        call_status.code = _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR
        call_status.error_buf = _UniffiFfiConverterString.lower(repr(e))
# Initial value and increment amount for handles. 
# These ensure that Python-generated handles always have the lowest bit set
_UNIFFI_HANDLEMAP_INITIAL = 1
_UNIFFI_HANDLEMAP_DELTA = 2

class _UniffiHandleMap:
    """
    A map where inserting, getting and removing data is synchronized with a lock.
    """

    def __init__(self):
        # type Handle = int
        self._map = {}  # type: Dict[Handle, Any]
        self._lock = threading.Lock()
        self._counter = _UNIFFI_HANDLEMAP_INITIAL

    def insert(self, obj):
        with self._lock:
            return self._insert(obj)

    """Low-level insert, this assumes `self._lock` is held."""
    def _insert(self, obj):
        handle = self._counter
        self._counter += _UNIFFI_HANDLEMAP_DELTA
        self._map[handle] = obj
        return handle

    def get(self, handle):
        try:
            with self._lock:
                return self._map[handle]
        except KeyError:
            raise InternalError(f"_UniffiHandleMap.get: Invalid handle {handle}")

    def clone(self, handle):
        try:
            with self._lock:
                obj = self._map[handle]
                return self._insert(obj)
        except KeyError:
            raise InternalError(f"_UniffiHandleMap.clone: Invalid handle {handle}")

    def remove(self, handle):
        try:
            with self._lock:
                return self._map.pop(handle)
        except KeyError:
            raise InternalError(f"_UniffiHandleMap.remove: Invalid handle: {handle}")

    def __len__(self):
        return len(self._map)
# Types conforming to `_UniffiConverterPrimitive` pass themselves directly over the FFI.
class _UniffiConverterPrimitive:
    @classmethod
    def lift(cls, value):
        return value

    @classmethod
    def lower(cls, value):
        return value

class _UniffiConverterPrimitiveInt(_UniffiConverterPrimitive):
    @classmethod
    def check_lower(cls, value):
        try:
            value = value.__index__()
        except Exception:
            raise TypeError("'{}' object cannot be interpreted as an integer".format(type(value).__name__))
        if not isinstance(value, int):
            raise TypeError("__index__ returned non-int (type {})".format(type(value).__name__))
        if not cls.VALUE_MIN <= value < cls.VALUE_MAX:
            raise ValueError("{} requires {} <= value < {}".format(cls.CLASS_NAME, cls.VALUE_MIN, cls.VALUE_MAX))

class _UniffiConverterPrimitiveFloat(_UniffiConverterPrimitive):
    @classmethod
    def check_lower(cls, value):
        try:
            value = value.__float__()
        except Exception:
            raise TypeError("must be real number, not {}".format(type(value).__name__))
        if not isinstance(value, float):
            raise TypeError("__float__ returned non-float (type {})".format(type(value).__name__))

# Helper class for wrapper types that will always go through a _UniffiRustBuffer.
# Classes should inherit from this and implement the `read` and `write` static methods.
class _UniffiConverterRustBuffer:
    @classmethod
    def lift(cls, rbuf):
        with rbuf.consume_with_stream() as stream:
            return cls.read(stream)

    @classmethod
    def lower(cls, value):
        with _UniffiRustBuffer.alloc_with_builder() as builder:
            cls.write(value, builder)
            return builder.finalize()

# Contains loading, initialization code, and the FFI Function declarations.
# Define some ctypes FFI types that we use in the library

"""
Function pointer for a Rust task, which a callback function that takes a opaque pointer
"""
_UNIFFI_RUST_TASK = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_int8)

def _uniffi_future_callback_t(return_type):
    """
    Factory function to create callback function types for async functions
    """
    return ctypes.CFUNCTYPE(None, ctypes.c_uint64, return_type, _UniffiRustCallStatus)

def _uniffi_load_indirect():
    """
    This is how we find and load the dynamic library provided by the component.
    For now we just look it up by name.
    """
    if sys.platform == "darwin":
        libname = "lib{}.dylib"
    elif sys.platform.startswith("win"):
        # As of python3.8, ctypes does not seem to search $PATH when loading DLLs.
        # We could use `os.add_dll_directory` to configure the search path, but
        # it doesn't feel right to mess with application-wide settings. Let's
        # assume that the `.dll` is next to the `.py` file and load by full path.
        libname = os.path.join(
            os.path.dirname(__file__),
            "{}.dll",
        )
    else:
        # Anything else must be an ELF platform - Linux, *BSD, Solaris/illumos
        libname = "lib{}.so"

    libname = libname.format("bkndb_ffi")
    path = os.path.join(os.path.dirname(__file__), libname)
    lib = ctypes.cdll.LoadLibrary(path)
    return lib

def _uniffi_check_contract_api_version(lib):
    # Get the bindings contract version from our ComponentInterface
    bindings_contract_version = 30
    # Get the scaffolding contract version by calling the into the dylib
    scaffolding_contract_version = lib.ffi_bkndb_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version:
        raise InternalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")

def _uniffi_check_api_checksums(lib):
    if lib.uniffi_bkndb_ffi_checksum_method_bkndbengine_cascade_delete() != 35560:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_bkndb_ffi_checksum_method_bkndbengine_create_edge() != 19597:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_bkndb_ffi_checksum_method_bkndbengine_create_edges_bulk() != 46431:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_bkndb_ffi_checksum_method_bkndbengine_create_node() != 55339:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_bkndb_ffi_checksum_method_bkndbengine_create_nodes_bulk() != 29999:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_bkndb_ffi_checksum_method_bkndbengine_delete_node() != 3983:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_bkndb_ffi_checksum_method_bkndbengine_find_shortest_path() != 36954:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_bkndb_ffi_checksum_method_bkndbengine_get_edge() != 45481:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_bkndb_ffi_checksum_method_bkndbengine_get_node() != 2294:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_bkndb_ffi_checksum_method_bkndbengine_neighbors_in() != 30079:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_bkndb_ffi_checksum_method_bkndbengine_neighbors_out() != 62954:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_bkndb_ffi_checksum_method_bkndbengine_sync_batch() != 57500:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_bkndb_ffi_checksum_method_bkndbengine_top_hubs() != 19397:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_bkndb_ffi_checksum_constructor_bkndbengine_in_memory() != 31228:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_bkndb_ffi_checksum_constructor_bkndbengine_open() != 51928:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")

# A ctypes library to expose the extern-C FFI definitions.
# This is an implementation detail which will be called internally by the public API.

_UniffiLib = _uniffi_load_indirect()
_UniffiLib.ffi_bkndb_ffi_rustbuffer_alloc.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_bkndb_ffi_rustbuffer_alloc.restype = _UniffiRustBuffer
_UniffiLib.ffi_bkndb_ffi_rustbuffer_from_bytes.argtypes = (
    _UniffiForeignBytes,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_bkndb_ffi_rustbuffer_from_bytes.restype = _UniffiRustBuffer
_UniffiLib.ffi_bkndb_ffi_rustbuffer_free.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_bkndb_ffi_rustbuffer_free.restype = None
_UniffiLib.ffi_bkndb_ffi_rustbuffer_reserve.argtypes = (
    _UniffiRustBuffer,
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_bkndb_ffi_rustbuffer_reserve.restype = _UniffiRustBuffer
_UniffiLib.ffi_bkndb_ffi_uniffi_contract_version.argtypes = (
)
_UniffiLib.ffi_bkndb_ffi_uniffi_contract_version.restype = ctypes.c_uint32
_UniffiLib.uniffi_bkndb_ffi_checksum_method_bkndbengine_cascade_delete.argtypes = (
)
_UniffiLib.uniffi_bkndb_ffi_checksum_method_bkndbengine_cascade_delete.restype = ctypes.c_uint16
_UniffiLib.uniffi_bkndb_ffi_checksum_method_bkndbengine_create_edge.argtypes = (
)
_UniffiLib.uniffi_bkndb_ffi_checksum_method_bkndbengine_create_edge.restype = ctypes.c_uint16
_UniffiLib.uniffi_bkndb_ffi_checksum_method_bkndbengine_create_edges_bulk.argtypes = (
)
_UniffiLib.uniffi_bkndb_ffi_checksum_method_bkndbengine_create_edges_bulk.restype = ctypes.c_uint16
_UniffiLib.uniffi_bkndb_ffi_checksum_method_bkndbengine_create_node.argtypes = (
)
_UniffiLib.uniffi_bkndb_ffi_checksum_method_bkndbengine_create_node.restype = ctypes.c_uint16
_UniffiLib.uniffi_bkndb_ffi_checksum_method_bkndbengine_create_nodes_bulk.argtypes = (
)
_UniffiLib.uniffi_bkndb_ffi_checksum_method_bkndbengine_create_nodes_bulk.restype = ctypes.c_uint16
_UniffiLib.uniffi_bkndb_ffi_checksum_method_bkndbengine_delete_node.argtypes = (
)
_UniffiLib.uniffi_bkndb_ffi_checksum_method_bkndbengine_delete_node.restype = ctypes.c_uint16
_UniffiLib.uniffi_bkndb_ffi_checksum_method_bkndbengine_find_shortest_path.argtypes = (
)
_UniffiLib.uniffi_bkndb_ffi_checksum_method_bkndbengine_find_shortest_path.restype = ctypes.c_uint16
_UniffiLib.uniffi_bkndb_ffi_checksum_method_bkndbengine_get_edge.argtypes = (
)
_UniffiLib.uniffi_bkndb_ffi_checksum_method_bkndbengine_get_edge.restype = ctypes.c_uint16
_UniffiLib.uniffi_bkndb_ffi_checksum_method_bkndbengine_get_node.argtypes = (
)
_UniffiLib.uniffi_bkndb_ffi_checksum_method_bkndbengine_get_node.restype = ctypes.c_uint16
_UniffiLib.uniffi_bkndb_ffi_checksum_method_bkndbengine_neighbors_in.argtypes = (
)
_UniffiLib.uniffi_bkndb_ffi_checksum_method_bkndbengine_neighbors_in.restype = ctypes.c_uint16
_UniffiLib.uniffi_bkndb_ffi_checksum_method_bkndbengine_neighbors_out.argtypes = (
)
_UniffiLib.uniffi_bkndb_ffi_checksum_method_bkndbengine_neighbors_out.restype = ctypes.c_uint16
_UniffiLib.uniffi_bkndb_ffi_checksum_method_bkndbengine_sync_batch.argtypes = (
)
_UniffiLib.uniffi_bkndb_ffi_checksum_method_bkndbengine_sync_batch.restype = ctypes.c_uint16
_UniffiLib.uniffi_bkndb_ffi_checksum_method_bkndbengine_top_hubs.argtypes = (
)
_UniffiLib.uniffi_bkndb_ffi_checksum_method_bkndbengine_top_hubs.restype = ctypes.c_uint16
_UniffiLib.uniffi_bkndb_ffi_checksum_constructor_bkndbengine_in_memory.argtypes = (
)
_UniffiLib.uniffi_bkndb_ffi_checksum_constructor_bkndbengine_in_memory.restype = ctypes.c_uint16
_UniffiLib.uniffi_bkndb_ffi_checksum_constructor_bkndbengine_open.argtypes = (
)
_UniffiLib.uniffi_bkndb_ffi_checksum_constructor_bkndbengine_open.restype = ctypes.c_uint16
_UniffiLib.uniffi_bkndb_ffi_fn_method_bkndbengine_cascade_delete.argtypes = (
    ctypes.c_uint64,
    ctypes.c_uint64,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_bkndb_ffi_fn_method_bkndbengine_cascade_delete.restype = _UniffiRustBuffer
_UniffiLib.uniffi_bkndb_ffi_fn_method_bkndbengine_create_edge.argtypes = (
    ctypes.c_uint64,
    ctypes.c_uint64,
    _UniffiRustBuffer,
    ctypes.c_uint64,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_bkndb_ffi_fn_method_bkndbengine_create_edge.restype = ctypes.c_uint64
_UniffiLib.uniffi_bkndb_ffi_fn_method_bkndbengine_create_edges_bulk.argtypes = (
    ctypes.c_uint64,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_bkndb_ffi_fn_method_bkndbengine_create_edges_bulk.restype = _UniffiRustBuffer
_UniffiLib.uniffi_bkndb_ffi_fn_method_bkndbengine_create_node.argtypes = (
    ctypes.c_uint64,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_bkndb_ffi_fn_method_bkndbengine_create_node.restype = ctypes.c_uint64
_UniffiLib.uniffi_bkndb_ffi_fn_method_bkndbengine_create_nodes_bulk.argtypes = (
    ctypes.c_uint64,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_bkndb_ffi_fn_method_bkndbengine_create_nodes_bulk.restype = _UniffiRustBuffer
_UniffiLib.uniffi_bkndb_ffi_fn_method_bkndbengine_delete_node.argtypes = (
    ctypes.c_uint64,
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_bkndb_ffi_fn_method_bkndbengine_delete_node.restype = None
_UniffiLib.uniffi_bkndb_ffi_fn_method_bkndbengine_find_shortest_path.argtypes = (
    ctypes.c_uint64,
    ctypes.c_uint64,
    ctypes.c_uint64,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_bkndb_ffi_fn_method_bkndbengine_find_shortest_path.restype = _UniffiRustBuffer
_UniffiLib.uniffi_bkndb_ffi_fn_method_bkndbengine_get_edge.argtypes = (
    ctypes.c_uint64,
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_bkndb_ffi_fn_method_bkndbengine_get_edge.restype = _UniffiRustBuffer
_UniffiLib.uniffi_bkndb_ffi_fn_method_bkndbengine_get_node.argtypes = (
    ctypes.c_uint64,
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_bkndb_ffi_fn_method_bkndbengine_get_node.restype = _UniffiRustBuffer
_UniffiLib.uniffi_bkndb_ffi_fn_method_bkndbengine_neighbors_in.argtypes = (
    ctypes.c_uint64,
    ctypes.c_uint64,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_bkndb_ffi_fn_method_bkndbengine_neighbors_in.restype = _UniffiRustBuffer
_UniffiLib.uniffi_bkndb_ffi_fn_method_bkndbengine_neighbors_out.argtypes = (
    ctypes.c_uint64,
    ctypes.c_uint64,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_bkndb_ffi_fn_method_bkndbengine_neighbors_out.restype = _UniffiRustBuffer
_UniffiLib.uniffi_bkndb_ffi_fn_method_bkndbengine_sync_batch.argtypes = (
    ctypes.c_uint64,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_bkndb_ffi_fn_method_bkndbengine_sync_batch.restype = _UniffiRustBuffer
_UniffiLib.uniffi_bkndb_ffi_fn_method_bkndbengine_top_hubs.argtypes = (
    ctypes.c_uint64,
    ctypes.c_uint32,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_bkndb_ffi_fn_method_bkndbengine_top_hubs.restype = _UniffiRustBuffer
_UniffiLib.uniffi_bkndb_ffi_fn_constructor_bkndbengine_in_memory.argtypes = (
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_bkndb_ffi_fn_constructor_bkndbengine_in_memory.restype = ctypes.c_uint64
_UniffiLib.uniffi_bkndb_ffi_fn_constructor_bkndbengine_open.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_bkndb_ffi_fn_constructor_bkndbengine_open.restype = ctypes.c_uint64
_UniffiLib.uniffi_bkndb_ffi_fn_clone_bkndbengine.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_bkndb_ffi_fn_clone_bkndbengine.restype = ctypes.c_uint64
_UniffiLib.uniffi_bkndb_ffi_fn_free_bkndbengine.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_bkndb_ffi_fn_free_bkndbengine.restype = None

_uniffi_check_contract_api_version(_UniffiLib)
# _uniffi_check_api_checksums(_UniffiLib)



# Public interface members begin here.


class _UniffiFfiConverterUInt64(_UniffiConverterPrimitiveInt):
    CLASS_NAME = "u64"
    VALUE_MIN = 0
    VALUE_MAX = 2**64

    @staticmethod
    def read(buf):
        return buf.read_u64()

    @staticmethod
    def write(value, buf):
        buf.write_u64(value)

class _UniffiFfiConverterString:
    @staticmethod
    def check_lower(value):
        if not isinstance(value, str):
            raise TypeError("argument must be str, not {}".format(type(value).__name__))
        return value

    @staticmethod
    def read(buf):
        size = buf.read_i32()
        if size < 0:
            raise InternalError("Unexpected negative string length")
        utf8_bytes = buf.read(size)
        return utf8_bytes.decode("utf-8")

    @staticmethod
    def write(value, buf):
        utf8_bytes = value.encode("utf-8")
        buf.write_i32(len(utf8_bytes))
        buf.write(utf8_bytes)

    @staticmethod
    def lift(buf):
        with buf.consume_with_stream() as stream:
            return stream.read(stream.remaining()).decode("utf-8")

    @staticmethod
    def lower(value):
        with _UniffiRustBuffer.alloc_with_builder() as builder:
            builder.write(value.encode("utf-8"))
            return builder.finalize()

class _UniffiFfiConverterInt64(_UniffiConverterPrimitiveInt):
    CLASS_NAME = "i64"
    VALUE_MIN = -2**63
    VALUE_MAX = 2**63

    @staticmethod
    def read(buf):
        return buf.read_i64()

    @staticmethod
    def write(value, buf):
        buf.write_i64(value)

class _UniffiFfiConverterFloat64(_UniffiConverterPrimitiveFloat):
    @staticmethod
    def read(buf):
        return buf.read_double()

    @staticmethod
    def write(value, buf):
        buf.write_double(value)

class _UniffiFfiConverterBoolean:
    @classmethod
    def check_lower(cls, value):
        return not not value

    @classmethod
    def lower(cls, value):
        return 1 if value else 0

    @staticmethod
    def lift(value):
        return value != 0

    @classmethod
    def read(cls, buf):
        return cls.lift(buf.read_u8())

    @classmethod
    def write(cls, value, buf):
        buf.write_u8(value)

class _UniffiFfiConverterBytes(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        size = buf.read_i32()
        if size < 0:
            raise InternalError("Unexpected negative byte string length")
        return buf.read(size)

    @staticmethod
    def check_lower(value):
        try:
            memoryview(value)
        except TypeError:
            raise TypeError("a bytes-like object is required, not {!r}".format(type(value).__name__))

    @staticmethod
    def write(value, buf):
        buf.write_i32(len(value))
        buf.write(value)






class FfiPropValue:
    def __init__(self):
        raise RuntimeError("FfiPropValue cannot be instantiated directly")

    # Each enum variant is a nested class of the enum itself.
    @dataclass
    class NULL:
        
        def __init__(self, ):
            pass

    
            
            
    
        def __str__(self):
            return "FfiPropValue.NULL()".format()
        def __eq__(self, other):
            if not isinstance(other, FfiPropValue):
                return NotImplemented
            if not other.is_NULL():
                return False
            return True

    @dataclass
    class STR:
        
        def __init__(self, *values):
            if len(values) != 1:
                raise TypeError(f"Expected 1 arguments, found {len(values)}")
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

    
            
            

    
        def __str__(self):
            return f"FfiPropValue.STR{self._values!r}"
        def __eq__(self, other):
            if not isinstance(other, FfiPropValue):
                return NotImplemented
            if not other.is_STR():
                return False
            return self._values == other._values

    @dataclass
    class INT:
        
        def __init__(self, *values):
            if len(values) != 1:
                raise TypeError(f"Expected 1 arguments, found {len(values)}")
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

    
            
            

    
        def __str__(self):
            return f"FfiPropValue.INT{self._values!r}"
        def __eq__(self, other):
            if not isinstance(other, FfiPropValue):
                return NotImplemented
            if not other.is_INT():
                return False
            return self._values == other._values

    @dataclass
    class FLOAT:
        
        def __init__(self, *values):
            if len(values) != 1:
                raise TypeError(f"Expected 1 arguments, found {len(values)}")
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

    
            
            

    
        def __str__(self):
            return f"FfiPropValue.FLOAT{self._values!r}"
        def __eq__(self, other):
            if not isinstance(other, FfiPropValue):
                return NotImplemented
            if not other.is_FLOAT():
                return False
            return self._values == other._values

    @dataclass
    class BOOL:
        
        def __init__(self, *values):
            if len(values) != 1:
                raise TypeError(f"Expected 1 arguments, found {len(values)}")
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

    
            
            

    
        def __str__(self):
            return f"FfiPropValue.BOOL{self._values!r}"
        def __eq__(self, other):
            if not isinstance(other, FfiPropValue):
                return NotImplemented
            if not other.is_BOOL():
                return False
            return self._values == other._values

    @dataclass
    class BYTES:
        
        def __init__(self, *values):
            if len(values) != 1:
                raise TypeError(f"Expected 1 arguments, found {len(values)}")
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

    
            
            

    
        def __str__(self):
            return f"FfiPropValue.BYTES{self._values!r}"
        def __eq__(self, other):
            if not isinstance(other, FfiPropValue):
                return NotImplemented
            if not other.is_BYTES():
                return False
            return self._values == other._values

    

    # For each variant, we have `is_NAME` and `is_name` methods for easily checking
    # whether an instance is that variant.
    def is_NULL(self) -> bool:
        return isinstance(self, FfiPropValue.NULL)
    def is_null(self) -> bool:
        return isinstance(self, FfiPropValue.NULL)
    def is_STR(self) -> bool:
        return isinstance(self, FfiPropValue.STR)
    def is_str(self) -> bool:
        return isinstance(self, FfiPropValue.STR)
    def is_INT(self) -> bool:
        return isinstance(self, FfiPropValue.INT)
    def is_int(self) -> bool:
        return isinstance(self, FfiPropValue.INT)
    def is_FLOAT(self) -> bool:
        return isinstance(self, FfiPropValue.FLOAT)
    def is_float(self) -> bool:
        return isinstance(self, FfiPropValue.FLOAT)
    def is_BOOL(self) -> bool:
        return isinstance(self, FfiPropValue.BOOL)
    def is_bool(self) -> bool:
        return isinstance(self, FfiPropValue.BOOL)
    def is_BYTES(self) -> bool:
        return isinstance(self, FfiPropValue.BYTES)
    def is_bytes(self) -> bool:
        return isinstance(self, FfiPropValue.BYTES)
    

# Now, a little trick - we make each nested variant class be a subclass of the main
# enum class, so that method calls and instance checks etc will work intuitively.
# We might be able to do this a little more neatly with a metaclass, but this'll do.
FfiPropValue.NULL = type("FfiPropValue.NULL", (FfiPropValue.NULL, FfiPropValue,), {})  # type: ignore
FfiPropValue.STR = type("FfiPropValue.STR", (FfiPropValue.STR, FfiPropValue,), {})  # type: ignore
FfiPropValue.INT = type("FfiPropValue.INT", (FfiPropValue.INT, FfiPropValue,), {})  # type: ignore
FfiPropValue.FLOAT = type("FfiPropValue.FLOAT", (FfiPropValue.FLOAT, FfiPropValue,), {})  # type: ignore
FfiPropValue.BOOL = type("FfiPropValue.BOOL", (FfiPropValue.BOOL, FfiPropValue,), {})  # type: ignore
FfiPropValue.BYTES = type("FfiPropValue.BYTES", (FfiPropValue.BYTES, FfiPropValue,), {})  # type: ignore




class _UniffiFfiConverterTypeFfiPropValue(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return FfiPropValue.NULL(
            )
        if variant == 2:
            return FfiPropValue.STR(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 3:
            return FfiPropValue.INT(
                _UniffiFfiConverterInt64.read(buf),
            )
        if variant == 4:
            return FfiPropValue.FLOAT(
                _UniffiFfiConverterFloat64.read(buf),
            )
        if variant == 5:
            return FfiPropValue.BOOL(
                _UniffiFfiConverterBoolean.read(buf),
            )
        if variant == 6:
            return FfiPropValue.BYTES(
                _UniffiFfiConverterBytes.read(buf),
            )
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value.is_NULL():
            return
        if value.is_STR():
            _UniffiFfiConverterString.check_lower(value._values[0])
            return
        if value.is_INT():
            _UniffiFfiConverterInt64.check_lower(value._values[0])
            return
        if value.is_FLOAT():
            _UniffiFfiConverterFloat64.check_lower(value._values[0])
            return
        if value.is_BOOL():
            _UniffiFfiConverterBoolean.check_lower(value._values[0])
            return
        if value.is_BYTES():
            _UniffiFfiConverterBytes.check_lower(value._values[0])
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value.is_NULL():
            buf.write_i32(1)
        if value.is_STR():
            buf.write_i32(2)
            _UniffiFfiConverterString.write(value._values[0], buf)
        if value.is_INT():
            buf.write_i32(3)
            _UniffiFfiConverterInt64.write(value._values[0], buf)
        if value.is_FLOAT():
            buf.write_i32(4)
            _UniffiFfiConverterFloat64.write(value._values[0], buf)
        if value.is_BOOL():
            buf.write_i32(5)
            _UniffiFfiConverterBoolean.write(value._values[0], buf)
        if value.is_BYTES():
            buf.write_i32(6)
            _UniffiFfiConverterBytes.write(value._values[0], buf)



class _UniffiFfiConverterMapStringTypeFfiPropValue(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, items):
        for (key, value) in items.items():
            _UniffiFfiConverterString.check_lower(key)
            _UniffiFfiConverterTypeFfiPropValue.check_lower(value)

    @classmethod
    def write(cls, items, buf):
        buf.write_i32(len(items))
        for (key, value) in items.items():
            _UniffiFfiConverterString.write(key, buf)
            _UniffiFfiConverterTypeFfiPropValue.write(value, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative map size")

        # It would be nice to use a dict comprehension,
        # but in Python 3.7 and before the evaluation order is not according to spec,
        # so we we're reading the value before the key.
        # This loop makes the order explicit: first reading the key, then the value.
        d = {}
        for i in range(count):
            key = _UniffiFfiConverterString.read(buf)
            val = _UniffiFfiConverterTypeFfiPropValue.read(buf)
            d[key] = val
        return d

@dataclass
class FfiEdgeInput:
    def __init__(self, *, _from:int, edge_type:str, to:int, properties:dict[str, FfiPropValue]):
        self._from = _from
        self.edge_type = edge_type
        self.to = to
        self.properties = properties
        
        

    
    def __str__(self):
        return "FfiEdgeInput(_from={}, edge_type={}, to={}, properties={})".format(self._from, self.edge_type, self.to, self.properties)
    def __eq__(self, other):
        if self._from != other._from:
            return False
        if self.edge_type != other.edge_type:
            return False
        if self.to != other.to:
            return False
        if self.properties != other.properties:
            return False
        return True

class _UniffiFfiConverterTypeFfiEdgeInput(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return FfiEdgeInput(
            _from=_UniffiFfiConverterUInt64.read(buf),
            edge_type=_UniffiFfiConverterString.read(buf),
            to=_UniffiFfiConverterUInt64.read(buf),
            properties=_UniffiFfiConverterMapStringTypeFfiPropValue.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterUInt64.check_lower(value._from)
        _UniffiFfiConverterString.check_lower(value.edge_type)
        _UniffiFfiConverterUInt64.check_lower(value.to)
        _UniffiFfiConverterMapStringTypeFfiPropValue.check_lower(value.properties)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterUInt64.write(value._from, buf)
        _UniffiFfiConverterString.write(value.edge_type, buf)
        _UniffiFfiConverterUInt64.write(value.to, buf)
        _UniffiFfiConverterMapStringTypeFfiPropValue.write(value.properties, buf)

@dataclass
class FfiEdgeRecord:
    def __init__(self, *, id:int, _from:int, to:int, edge_type:str, properties:dict[str, FfiPropValue]):
        self.id = id
        self._from = _from
        self.to = to
        self.edge_type = edge_type
        self.properties = properties
        
        

    
    def __str__(self):
        return "FfiEdgeRecord(id={}, _from={}, to={}, edge_type={}, properties={})".format(self.id, self._from, self.to, self.edge_type, self.properties)
    def __eq__(self, other):
        if self.id != other.id:
            return False
        if self._from != other._from:
            return False
        if self.to != other.to:
            return False
        if self.edge_type != other.edge_type:
            return False
        if self.properties != other.properties:
            return False
        return True

class _UniffiFfiConverterTypeFfiEdgeRecord(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return FfiEdgeRecord(
            id=_UniffiFfiConverterUInt64.read(buf),
            _from=_UniffiFfiConverterUInt64.read(buf),
            to=_UniffiFfiConverterUInt64.read(buf),
            edge_type=_UniffiFfiConverterString.read(buf),
            properties=_UniffiFfiConverterMapStringTypeFfiPropValue.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterUInt64.check_lower(value.id)
        _UniffiFfiConverterUInt64.check_lower(value._from)
        _UniffiFfiConverterUInt64.check_lower(value.to)
        _UniffiFfiConverterString.check_lower(value.edge_type)
        _UniffiFfiConverterMapStringTypeFfiPropValue.check_lower(value.properties)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterUInt64.write(value.id, buf)
        _UniffiFfiConverterUInt64.write(value._from, buf)
        _UniffiFfiConverterUInt64.write(value.to, buf)
        _UniffiFfiConverterString.write(value.edge_type, buf)
        _UniffiFfiConverterMapStringTypeFfiPropValue.write(value.properties, buf)

@dataclass
class FfiHubRecord:
    def __init__(self, *, node_id:int, degree:int):
        self.node_id = node_id
        self.degree = degree
        
        

    
    def __str__(self):
        return "FfiHubRecord(node_id={}, degree={})".format(self.node_id, self.degree)
    def __eq__(self, other):
        if self.node_id != other.node_id:
            return False
        if self.degree != other.degree:
            return False
        return True

class _UniffiFfiConverterTypeFfiHubRecord(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return FfiHubRecord(
            node_id=_UniffiFfiConverterUInt64.read(buf),
            degree=_UniffiFfiConverterUInt64.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterUInt64.check_lower(value.node_id)
        _UniffiFfiConverterUInt64.check_lower(value.degree)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterUInt64.write(value.node_id, buf)
        _UniffiFfiConverterUInt64.write(value.degree, buf)

@dataclass
class FfiNeighbor:
    def __init__(self, *, node_id:int, edge_id:int):
        self.node_id = node_id
        self.edge_id = edge_id
        
        

    
    def __str__(self):
        return "FfiNeighbor(node_id={}, edge_id={})".format(self.node_id, self.edge_id)
    def __eq__(self, other):
        if self.node_id != other.node_id:
            return False
        if self.edge_id != other.edge_id:
            return False
        return True

class _UniffiFfiConverterTypeFfiNeighbor(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return FfiNeighbor(
            node_id=_UniffiFfiConverterUInt64.read(buf),
            edge_id=_UniffiFfiConverterUInt64.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterUInt64.check_lower(value.node_id)
        _UniffiFfiConverterUInt64.check_lower(value.edge_id)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterUInt64.write(value.node_id, buf)
        _UniffiFfiConverterUInt64.write(value.edge_id, buf)

@dataclass
class FfiNodeInput:
    def __init__(self, *, label:str, properties:dict[str, FfiPropValue]):
        self.label = label
        self.properties = properties
        
        

    
    def __str__(self):
        return "FfiNodeInput(label={}, properties={})".format(self.label, self.properties)
    def __eq__(self, other):
        if self.label != other.label:
            return False
        if self.properties != other.properties:
            return False
        return True

class _UniffiFfiConverterTypeFfiNodeInput(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return FfiNodeInput(
            label=_UniffiFfiConverterString.read(buf),
            properties=_UniffiFfiConverterMapStringTypeFfiPropValue.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterString.check_lower(value.label)
        _UniffiFfiConverterMapStringTypeFfiPropValue.check_lower(value.properties)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterString.write(value.label, buf)
        _UniffiFfiConverterMapStringTypeFfiPropValue.write(value.properties, buf)

@dataclass
class FfiNodeRecord:
    def __init__(self, *, id:int, label:str, properties:dict[str, FfiPropValue]):
        self.id = id
        self.label = label
        self.properties = properties
        
        

    
    def __str__(self):
        return "FfiNodeRecord(id={}, label={}, properties={})".format(self.id, self.label, self.properties)
    def __eq__(self, other):
        if self.id != other.id:
            return False
        if self.label != other.label:
            return False
        if self.properties != other.properties:
            return False
        return True

class _UniffiFfiConverterTypeFfiNodeRecord(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return FfiNodeRecord(
            id=_UniffiFfiConverterUInt64.read(buf),
            label=_UniffiFfiConverterString.read(buf),
            properties=_UniffiFfiConverterMapStringTypeFfiPropValue.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterUInt64.check_lower(value.id)
        _UniffiFfiConverterString.check_lower(value.label)
        _UniffiFfiConverterMapStringTypeFfiPropValue.check_lower(value.properties)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterUInt64.write(value.id, buf)
        _UniffiFfiConverterString.write(value.label, buf)
        _UniffiFfiConverterMapStringTypeFfiPropValue.write(value.properties, buf)

class _UniffiFfiConverterOptionalUInt64(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiFfiConverterUInt64.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiFfiConverterUInt64.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiFfiConverterUInt64.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")

class _UniffiFfiConverterOptionalString(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiFfiConverterString.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiFfiConverterString.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiFfiConverterString.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")

@dataclass
class FfiPathStep:
    def __init__(self, *, node_id:int, via_edge_id:typing.Optional[int], edge_type:typing.Optional[str]):
        self.node_id = node_id
        self.via_edge_id = via_edge_id
        self.edge_type = edge_type
        
        

    
    def __str__(self):
        return "FfiPathStep(node_id={}, via_edge_id={}, edge_type={})".format(self.node_id, self.via_edge_id, self.edge_type)
    def __eq__(self, other):
        if self.node_id != other.node_id:
            return False
        if self.via_edge_id != other.via_edge_id:
            return False
        if self.edge_type != other.edge_type:
            return False
        return True

class _UniffiFfiConverterTypeFfiPathStep(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return FfiPathStep(
            node_id=_UniffiFfiConverterUInt64.read(buf),
            via_edge_id=_UniffiFfiConverterOptionalUInt64.read(buf),
            edge_type=_UniffiFfiConverterOptionalString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterUInt64.check_lower(value.node_id)
        _UniffiFfiConverterOptionalUInt64.check_lower(value.via_edge_id)
        _UniffiFfiConverterOptionalString.check_lower(value.edge_type)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterUInt64.write(value.node_id, buf)
        _UniffiFfiConverterOptionalUInt64.write(value.via_edge_id, buf)
        _UniffiFfiConverterOptionalString.write(value.edge_type, buf)

class _UniffiFfiConverterSequenceTypeFfiPathStep(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiFfiConverterTypeFfiPathStep.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiFfiConverterTypeFfiPathStep.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiFfiConverterTypeFfiPathStep.read(buf) for i in range(count)
        ]

class _UniffiFfiConverterSequenceUInt64(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiFfiConverterUInt64.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiFfiConverterUInt64.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiFfiConverterUInt64.read(buf) for i in range(count)
        ]

@dataclass
class FfiPathResult:
    def __init__(self, *, steps:typing.List[FfiPathStep], node_ids:typing.List[int], edge_ids:typing.List[int]):
        self.steps = steps
        self.node_ids = node_ids
        self.edge_ids = edge_ids
        
        

    
    def __str__(self):
        return "FfiPathResult(steps={}, node_ids={}, edge_ids={})".format(self.steps, self.node_ids, self.edge_ids)
    def __eq__(self, other):
        if self.steps != other.steps:
            return False
        if self.node_ids != other.node_ids:
            return False
        if self.edge_ids != other.edge_ids:
            return False
        return True

class _UniffiFfiConverterTypeFfiPathResult(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return FfiPathResult(
            steps=_UniffiFfiConverterSequenceTypeFfiPathStep.read(buf),
            node_ids=_UniffiFfiConverterSequenceUInt64.read(buf),
            edge_ids=_UniffiFfiConverterSequenceUInt64.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterSequenceTypeFfiPathStep.check_lower(value.steps)
        _UniffiFfiConverterSequenceUInt64.check_lower(value.node_ids)
        _UniffiFfiConverterSequenceUInt64.check_lower(value.edge_ids)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterSequenceTypeFfiPathStep.write(value.steps, buf)
        _UniffiFfiConverterSequenceUInt64.write(value.node_ids, buf)
        _UniffiFfiConverterSequenceUInt64.write(value.edge_ids, buf)

class _UniffiFfiConverterSequenceTypeFfiNodeInput(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiFfiConverterTypeFfiNodeInput.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiFfiConverterTypeFfiNodeInput.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiFfiConverterTypeFfiNodeInput.read(buf) for i in range(count)
        ]

class _UniffiFfiConverterSequenceTypeFfiEdgeInput(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiFfiConverterTypeFfiEdgeInput.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiFfiConverterTypeFfiEdgeInput.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiFfiConverterTypeFfiEdgeInput.read(buf) for i in range(count)
        ]

@dataclass
class FfiSyncBatch:
    def __init__(self, *, nodes:typing.List[FfiNodeInput], edges:typing.List[FfiEdgeInput]):
        self.nodes = nodes
        self.edges = edges
        
        

    
    def __str__(self):
        return "FfiSyncBatch(nodes={}, edges={})".format(self.nodes, self.edges)
    def __eq__(self, other):
        if self.nodes != other.nodes:
            return False
        if self.edges != other.edges:
            return False
        return True

class _UniffiFfiConverterTypeFfiSyncBatch(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return FfiSyncBatch(
            nodes=_UniffiFfiConverterSequenceTypeFfiNodeInput.read(buf),
            edges=_UniffiFfiConverterSequenceTypeFfiEdgeInput.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterSequenceTypeFfiNodeInput.check_lower(value.nodes)
        _UniffiFfiConverterSequenceTypeFfiEdgeInput.check_lower(value.edges)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterSequenceTypeFfiNodeInput.write(value.nodes, buf)
        _UniffiFfiConverterSequenceTypeFfiEdgeInput.write(value.edges, buf)

@dataclass
class FfiSyncResult:
    def __init__(self, *, node_ids:typing.List[int], edge_ids:typing.List[int]):
        self.node_ids = node_ids
        self.edge_ids = edge_ids
        
        

    
    def __str__(self):
        return "FfiSyncResult(node_ids={}, edge_ids={})".format(self.node_ids, self.edge_ids)
    def __eq__(self, other):
        if self.node_ids != other.node_ids:
            return False
        if self.edge_ids != other.edge_ids:
            return False
        return True

class _UniffiFfiConverterTypeFfiSyncResult(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return FfiSyncResult(
            node_ids=_UniffiFfiConverterSequenceUInt64.read(buf),
            edge_ids=_UniffiFfiConverterSequenceUInt64.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiFfiConverterSequenceUInt64.check_lower(value.node_ids)
        _UniffiFfiConverterSequenceUInt64.check_lower(value.edge_ids)

    @staticmethod
    def write(value, buf):
        _UniffiFfiConverterSequenceUInt64.write(value.node_ids, buf)
        _UniffiFfiConverterSequenceUInt64.write(value.edge_ids, buf)



# FfiBknError
# We want to define each variant as a nested class that's also a subclass,
# which is tricky in Python.  To accomplish this we're going to create each
# class separately, then manually add the child classes to the base class's
# __dict__.  All of this happens in dummy class to avoid polluting the module
# namespace.
class FfiBknError(Exception):
    pass

_UniffiTempFfiBknError = FfiBknError

class FfiBknError:  # type: ignore
    
    class Backend(_UniffiTempFfiBknError):
        
        def __init__(self, message):
            super().__init__(", ".join([
                "message={!r}".format(message),
            ]))
            self.message = message

        def __repr__(self):
            return "FfiBknError.Backend({})".format(str(self))
    _UniffiTempFfiBknError.Backend = Backend # type: ignore
    class TableNotFound(_UniffiTempFfiBknError):
        
        def __init__(self, table):
            super().__init__(", ".join([
                "table={!r}".format(table),
            ]))
            self.table = table

        def __repr__(self):
            return "FfiBknError.TableNotFound({})".format(str(self))
    _UniffiTempFfiBknError.TableNotFound = TableNotFound # type: ignore
    class NotFound(_UniffiTempFfiBknError):
        
        def __init__(self):
            pass

        def __repr__(self):
            return "FfiBknError.NotFound({})".format(str(self))
    _UniffiTempFfiBknError.NotFound = NotFound # type: ignore
    class Encoding(_UniffiTempFfiBknError):
        
        def __init__(self, message):
            super().__init__(", ".join([
                "message={!r}".format(message),
            ]))
            self.message = message

        def __repr__(self):
            return "FfiBknError.Encoding({})".format(str(self))
    _UniffiTempFfiBknError.Encoding = Encoding # type: ignore
    class ReservedTableName(_UniffiTempFfiBknError):
        
        def __init__(self, table):
            super().__init__(", ".join([
                "table={!r}".format(table),
            ]))
            self.table = table

        def __repr__(self):
            return "FfiBknError.ReservedTableName({})".format(str(self))
    _UniffiTempFfiBknError.ReservedTableName = ReservedTableName # type: ignore

FfiBknError = _UniffiTempFfiBknError # type: ignore
del _UniffiTempFfiBknError


class _UniffiFfiConverterTypeFfiBknError(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return FfiBknError.Backend(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 2:
            return FfiBknError.TableNotFound(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 3:
            return FfiBknError.NotFound(
            )
        if variant == 4:
            return FfiBknError.Encoding(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 5:
            return FfiBknError.ReservedTableName(
                _UniffiFfiConverterString.read(buf),
            )
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if isinstance(value, FfiBknError.Backend):
            _UniffiFfiConverterString.check_lower(value.message)
            return
        if isinstance(value, FfiBknError.TableNotFound):
            _UniffiFfiConverterString.check_lower(value.table)
            return
        if isinstance(value, FfiBknError.NotFound):
            return
        if isinstance(value, FfiBknError.Encoding):
            _UniffiFfiConverterString.check_lower(value.message)
            return
        if isinstance(value, FfiBknError.ReservedTableName):
            _UniffiFfiConverterString.check_lower(value.table)
            return

    @staticmethod
    def write(value, buf):
        if isinstance(value, FfiBknError.Backend):
            buf.write_i32(1)
            _UniffiFfiConverterString.write(value.message, buf)
        if isinstance(value, FfiBknError.TableNotFound):
            buf.write_i32(2)
            _UniffiFfiConverterString.write(value.table, buf)
        if isinstance(value, FfiBknError.NotFound):
            buf.write_i32(3)
        if isinstance(value, FfiBknError.Encoding):
            buf.write_i32(4)
            _UniffiFfiConverterString.write(value.message, buf)
        if isinstance(value, FfiBknError.ReservedTableName):
            buf.write_i32(5)
            _UniffiFfiConverterString.write(value.table, buf)






class FfiDirection(enum.Enum):
    
    OUT = 0
    
    IN = 1
    
    BOTH = 2
    


class _UniffiFfiConverterTypeFfiDirection(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return FfiDirection.OUT
        if variant == 2:
            return FfiDirection.IN
        if variant == 3:
            return FfiDirection.BOTH
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value == FfiDirection.OUT:
            return
        if value == FfiDirection.IN:
            return
        if value == FfiDirection.BOTH:
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value == FfiDirection.OUT:
            buf.write_i32(1)
        if value == FfiDirection.IN:
            buf.write_i32(2)
        if value == FfiDirection.BOTH:
            buf.write_i32(3)



class _UniffiFfiConverterSequenceString(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiFfiConverterString.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiFfiConverterString.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiFfiConverterString.read(buf) for i in range(count)
        ]

class _UniffiFfiConverterOptionalSequenceString(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiFfiConverterSequenceString.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiFfiConverterSequenceString.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiFfiConverterSequenceString.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")

class _UniffiFfiConverterOptionalTypeFfiPathResult(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiFfiConverterTypeFfiPathResult.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiFfiConverterTypeFfiPathResult.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiFfiConverterTypeFfiPathResult.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")

class _UniffiFfiConverterOptionalTypeFfiEdgeRecord(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiFfiConverterTypeFfiEdgeRecord.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiFfiConverterTypeFfiEdgeRecord.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiFfiConverterTypeFfiEdgeRecord.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")

class _UniffiFfiConverterOptionalTypeFfiNodeRecord(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiFfiConverterTypeFfiNodeRecord.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiFfiConverterTypeFfiNodeRecord.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiFfiConverterTypeFfiNodeRecord.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")

class _UniffiFfiConverterSequenceTypeFfiNeighbor(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiFfiConverterTypeFfiNeighbor.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiFfiConverterTypeFfiNeighbor.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiFfiConverterTypeFfiNeighbor.read(buf) for i in range(count)
        ]

class _UniffiFfiConverterUInt32(_UniffiConverterPrimitiveInt):
    CLASS_NAME = "u32"
    VALUE_MIN = 0
    VALUE_MAX = 2**32

    @staticmethod
    def read(buf):
        return buf.read_u32()

    @staticmethod
    def write(value, buf):
        buf.write_u32(value)

class _UniffiFfiConverterSequenceTypeFfiHubRecord(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiFfiConverterTypeFfiHubRecord.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiFfiConverterTypeFfiHubRecord.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiFfiConverterTypeFfiHubRecord.read(buf) for i in range(count)
        ]


class BknDbEngineProtocol(typing.Protocol):
    """
    The main mobile entrypoint for BknDb, thread-safe and exported via UniFFI.
"""
    
    def cascade_delete(self, root: int,containment_edge: str) -> typing.List[int]:
        """
        Recursively cascade-deletes `root` and all descendants reachable via `containment_edge`.
"""
        raise NotImplementedError
    def create_edge(self, _from: int,edge_type: str,to: int,properties: dict[str, FfiPropValue]) -> int:
        """
        Creates a directed edge between two existing nodes.
"""
        raise NotImplementedError
    def create_edges_bulk(self, edges: typing.List[FfiEdgeInput]) -> typing.List[int]:
        """
        Creates multiple edges in a single atomic transaction.
"""
        raise NotImplementedError
    def create_node(self, label: str,properties: dict[str, FfiPropValue]) -> int:
        """
        Creates a single graph node with the given label and properties.
"""
        raise NotImplementedError
    def create_nodes_bulk(self, nodes: typing.List[FfiNodeInput]) -> typing.List[int]:
        """
        Creates multiple nodes in a single atomic transaction.
"""
        raise NotImplementedError
    def delete_node(self, id: int) -> None:
        """
        Deletes a node and all incident edges atomically.
"""
        raise NotImplementedError
    def find_shortest_path(self, start: int,target: int,direction: FfiDirection,edge_types: typing.Optional[typing.List[str]]) -> typing.Optional[FfiPathResult]:
        """
        Computes the unweighted shortest path between `start` and `target` using BFS.
"""
        raise NotImplementedError
    def get_edge(self, id: int) -> typing.Optional[FfiEdgeRecord]:
        """
        Retrieves an edge by its numeric ID.
"""
        raise NotImplementedError
    def get_node(self, id: int) -> typing.Optional[FfiNodeRecord]:
        """
        Retrieves a node by its numeric ID.
"""
        raise NotImplementedError
    def neighbors_in(self, node: int,edge_type: str) -> typing.List[FfiNeighbor]:
        """
        Returns incoming neighbors for `node` along edges of type `edge_type`.
"""
        raise NotImplementedError
    def neighbors_out(self, node: int,edge_type: str) -> typing.List[FfiNeighbor]:
        """
        Returns outgoing neighbors for `node` along edges of type `edge_type`.
"""
        raise NotImplementedError
    def sync_batch(self, batch: FfiSyncBatch) -> FfiSyncResult:
        """
        Ingests a structured batch of graph nodes and edges in a single atomic transaction.
"""
        raise NotImplementedError
    def top_hubs(self, k: int,direction: FfiDirection,edge_type: typing.Optional[str]) -> typing.List[FfiHubRecord]:
        """
        Finds the top `k` hub nodes by degree centrality, optionally filtered by edge type.
"""
        raise NotImplementedError

class BknDbEngine(BknDbEngineProtocol):
    """
    The main mobile entrypoint for BknDb, thread-safe and exported via UniFFI.
"""
    
    _handle: ctypes.c_uint64
    @classmethod
    def in_memory(cls, ) -> BknDbEngine:
        """
        Creates an ephemeral in-memory database instance.
"""
        _uniffi_lowered_args = (
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeBknDbEngine.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeFfiBknError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_bkndb_ffi_fn_constructor_bkndbengine_in_memory,
            *_uniffi_lowered_args,
        )
        return cls._uniffi_make_instance(_uniffi_ffi_result)
    @classmethod
    def open(cls, path: str) -> BknDbEngine:
        """
        Opens or creates an on-disk single-file database at `path`.
"""
        
        _UniffiFfiConverterString.check_lower(path)
        _uniffi_lowered_args = (
            _UniffiFfiConverterString.lower(path),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeBknDbEngine.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeFfiBknError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_bkndb_ffi_fn_constructor_bkndbengine_open,
            *_uniffi_lowered_args,
        )
        return cls._uniffi_make_instance(_uniffi_ffi_result)
    
    def __init__(self, *args, **kwargs):
        raise ValueError("This class has no default constructor")

    def __del__(self):
        # In case of partial initialization of instances.
        handle = getattr(self, "_handle", None)
        if handle is not None:
            _uniffi_rust_call(_UniffiLib.uniffi_bkndb_ffi_fn_free_bkndbengine, handle)

    def _uniffi_clone_handle(self):
        return _uniffi_rust_call(_UniffiLib.uniffi_bkndb_ffi_fn_clone_bkndbengine, self._handle)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _uniffi_make_instance(cls, handle):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required handle.
        inst = cls.__new__(cls)
        inst._handle = handle
        return inst
    def cascade_delete(self, root: int,containment_edge: str) -> typing.List[int]:
        """
        Recursively cascade-deletes `root` and all descendants reachable via `containment_edge`.
"""
        
        _UniffiFfiConverterUInt64.check_lower(root)

        _UniffiFfiConverterString.check_lower(containment_edge)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            _UniffiFfiConverterUInt64.lower(root),
            _UniffiFfiConverterString.lower(containment_edge),
        )
        _uniffi_lift_return = _UniffiFfiConverterSequenceUInt64.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeFfiBknError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_bkndb_ffi_fn_method_bkndbengine_cascade_delete,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def create_edge(self, _from: int,edge_type: str,to: int,properties: dict[str, FfiPropValue]) -> int:
        """
        Creates a directed edge between two existing nodes.
"""
        
        _UniffiFfiConverterUInt64.check_lower(_from)

        _UniffiFfiConverterString.check_lower(edge_type)

        _UniffiFfiConverterUInt64.check_lower(to)

        _UniffiFfiConverterMapStringTypeFfiPropValue.check_lower(properties)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            _UniffiFfiConverterUInt64.lower(_from),
            _UniffiFfiConverterString.lower(edge_type),
            _UniffiFfiConverterUInt64.lower(to),
            _UniffiFfiConverterMapStringTypeFfiPropValue.lower(properties),
        )
        _uniffi_lift_return = _UniffiFfiConverterUInt64.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeFfiBknError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_bkndb_ffi_fn_method_bkndbengine_create_edge,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def create_edges_bulk(self, edges: typing.List[FfiEdgeInput]) -> typing.List[int]:
        """
        Creates multiple edges in a single atomic transaction.
"""
        
        _UniffiFfiConverterSequenceTypeFfiEdgeInput.check_lower(edges)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            _UniffiFfiConverterSequenceTypeFfiEdgeInput.lower(edges),
        )
        _uniffi_lift_return = _UniffiFfiConverterSequenceUInt64.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeFfiBknError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_bkndb_ffi_fn_method_bkndbengine_create_edges_bulk,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def create_node(self, label: str,properties: dict[str, FfiPropValue]) -> int:
        """
        Creates a single graph node with the given label and properties.
"""
        
        _UniffiFfiConverterString.check_lower(label)

        _UniffiFfiConverterMapStringTypeFfiPropValue.check_lower(properties)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            _UniffiFfiConverterString.lower(label),
            _UniffiFfiConverterMapStringTypeFfiPropValue.lower(properties),
        )
        _uniffi_lift_return = _UniffiFfiConverterUInt64.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeFfiBknError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_bkndb_ffi_fn_method_bkndbengine_create_node,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def create_nodes_bulk(self, nodes: typing.List[FfiNodeInput]) -> typing.List[int]:
        """
        Creates multiple nodes in a single atomic transaction.
"""
        
        _UniffiFfiConverterSequenceTypeFfiNodeInput.check_lower(nodes)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            _UniffiFfiConverterSequenceTypeFfiNodeInput.lower(nodes),
        )
        _uniffi_lift_return = _UniffiFfiConverterSequenceUInt64.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeFfiBknError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_bkndb_ffi_fn_method_bkndbengine_create_nodes_bulk,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def delete_node(self, id: int) -> None:
        """
        Deletes a node and all incident edges atomically.
"""
        
        _UniffiFfiConverterUInt64.check_lower(id)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            _UniffiFfiConverterUInt64.lower(id),
        )
        _uniffi_lift_return = lambda val: None
        _uniffi_error_converter = _UniffiFfiConverterTypeFfiBknError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_bkndb_ffi_fn_method_bkndbengine_delete_node,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def find_shortest_path(self, start: int,target: int,direction: FfiDirection,edge_types: typing.Optional[typing.List[str]]) -> typing.Optional[FfiPathResult]:
        """
        Computes the unweighted shortest path between `start` and `target` using BFS.
"""
        
        _UniffiFfiConverterUInt64.check_lower(start)

        _UniffiFfiConverterUInt64.check_lower(target)

        _UniffiFfiConverterTypeFfiDirection.check_lower(direction)

        _UniffiFfiConverterOptionalSequenceString.check_lower(edge_types)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            _UniffiFfiConverterUInt64.lower(start),
            _UniffiFfiConverterUInt64.lower(target),
            _UniffiFfiConverterTypeFfiDirection.lower(direction),
            _UniffiFfiConverterOptionalSequenceString.lower(edge_types),
        )
        _uniffi_lift_return = _UniffiFfiConverterOptionalTypeFfiPathResult.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeFfiBknError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_bkndb_ffi_fn_method_bkndbengine_find_shortest_path,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def get_edge(self, id: int) -> typing.Optional[FfiEdgeRecord]:
        """
        Retrieves an edge by its numeric ID.
"""
        
        _UniffiFfiConverterUInt64.check_lower(id)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            _UniffiFfiConverterUInt64.lower(id),
        )
        _uniffi_lift_return = _UniffiFfiConverterOptionalTypeFfiEdgeRecord.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeFfiBknError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_bkndb_ffi_fn_method_bkndbengine_get_edge,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def get_node(self, id: int) -> typing.Optional[FfiNodeRecord]:
        """
        Retrieves a node by its numeric ID.
"""
        
        _UniffiFfiConverterUInt64.check_lower(id)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            _UniffiFfiConverterUInt64.lower(id),
        )
        _uniffi_lift_return = _UniffiFfiConverterOptionalTypeFfiNodeRecord.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeFfiBknError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_bkndb_ffi_fn_method_bkndbengine_get_node,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def neighbors_in(self, node: int,edge_type: str) -> typing.List[FfiNeighbor]:
        """
        Returns incoming neighbors for `node` along edges of type `edge_type`.
"""
        
        _UniffiFfiConverterUInt64.check_lower(node)

        _UniffiFfiConverterString.check_lower(edge_type)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            _UniffiFfiConverterUInt64.lower(node),
            _UniffiFfiConverterString.lower(edge_type),
        )
        _uniffi_lift_return = _UniffiFfiConverterSequenceTypeFfiNeighbor.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeFfiBknError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_bkndb_ffi_fn_method_bkndbengine_neighbors_in,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def neighbors_out(self, node: int,edge_type: str) -> typing.List[FfiNeighbor]:
        """
        Returns outgoing neighbors for `node` along edges of type `edge_type`.
"""
        
        _UniffiFfiConverterUInt64.check_lower(node)

        _UniffiFfiConverterString.check_lower(edge_type)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            _UniffiFfiConverterUInt64.lower(node),
            _UniffiFfiConverterString.lower(edge_type),
        )
        _uniffi_lift_return = _UniffiFfiConverterSequenceTypeFfiNeighbor.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeFfiBknError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_bkndb_ffi_fn_method_bkndbengine_neighbors_out,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def sync_batch(self, batch: FfiSyncBatch) -> FfiSyncResult:
        """
        Ingests a structured batch of graph nodes and edges in a single atomic transaction.
"""
        
        _UniffiFfiConverterTypeFfiSyncBatch.check_lower(batch)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            _UniffiFfiConverterTypeFfiSyncBatch.lower(batch),
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeFfiSyncResult.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeFfiBknError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_bkndb_ffi_fn_method_bkndbengine_sync_batch,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)
    def top_hubs(self, k: int,direction: FfiDirection,edge_type: typing.Optional[str]) -> typing.List[FfiHubRecord]:
        """
        Finds the top `k` hub nodes by degree centrality, optionally filtered by edge type.
"""
        
        _UniffiFfiConverterUInt32.check_lower(k)

        _UniffiFfiConverterTypeFfiDirection.check_lower(direction)

        _UniffiFfiConverterOptionalString.check_lower(edge_type)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            _UniffiFfiConverterUInt32.lower(k),
            _UniffiFfiConverterTypeFfiDirection.lower(direction),
            _UniffiFfiConverterOptionalString.lower(edge_type),
        )
        _uniffi_lift_return = _UniffiFfiConverterSequenceTypeFfiHubRecord.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeFfiBknError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_bkndb_ffi_fn_method_bkndbengine_top_hubs,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)





class _UniffiFfiConverterTypeBknDbEngine:
    @staticmethod
    def lift(value: int) -> BknDbEngine:
        return BknDbEngine._uniffi_make_instance(value)

    @staticmethod
    def check_lower(value: BknDbEngine):
        if not isinstance(value, BknDbEngine):
            raise TypeError("Expected BknDbEngine instance, {} found".format(type(value).__name__))

    @staticmethod
    def lower(value: BknDbEngine) -> ctypes.c_uint64:
        return value._uniffi_clone_handle()

    @classmethod
    def read(cls, buf: _UniffiRustBuffer) -> BknDbEngine:
        ptr = buf.read_u64()
        if ptr == 0:
            raise InternalError("Raw handle value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value: BknDbEngine, buf: _UniffiRustBuffer):
        buf.write_u64(cls.lower(value))

__all__ = [
    "InternalError",
    "FfiPropValue",
    "FfiBknError",
    "FfiDirection",
    "FfiEdgeInput",
    "FfiEdgeRecord",
    "FfiHubRecord",
    "FfiNeighbor",
    "FfiNodeInput",
    "FfiNodeRecord",
    "FfiPathStep",
    "FfiPathResult",
    "FfiSyncBatch",
    "FfiSyncResult",
    "BknDbEngine",
    "BknDbEngineProtocol",
]