// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(bkndb_ffiFFI)
import bkndb_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_bkndb_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_bkndb_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }

    init(rawBufferPointer: UnsafeRawBufferPointer) {
        self.init(
            len: Int32(rawBufferPointer.count),
            data: rawBufferPointer.baseAddress?.assumingMemoryBound(to: UInt8.self)
        )
    }
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Conforms to `FfiConverter` so the compiler enforces the full converter
// method set. Only the scope-bound `lower(_:_body:)` overload is sound —
// zero-copy byte buffers only flow foreign -> Rust, and only in argument
// position. The four protocol-witness methods (`lift`, `lower`, `read`,
// `write`) `fatalError` at runtime if anyone reaches them.
//
// The scope-bound `lower` takes a closure because the `ForeignBytes`
// pointer is only guaranteed valid for the duration of
// `Data.withUnsafeBytes`. Callers must run the full FFI call inside
// the closure body.
fileprivate enum FfiConverterByRefBytes: FfiConverter {
    typealias SwiftType = Data
    typealias FfiType = ForeignBytes

    static func lower<R>(_ value: Data, _ body: (ForeignBytes) throws -> R) rethrows -> R {
        return try value.withUnsafeBytes { rawBuf in
            try body(ForeignBytes(rawBufferPointer: rawBuf))
        }
    }

    static func lower(_ value: Data) -> ForeignBytes {
        fatalError("ByRef bytes cannot use the plain lower: returning ForeignBytes escapes the Data.withUnsafeBytes scope. Use the scope-bound lower(_:_body:) overload instead.")
    }

    static func lift(_ value: ForeignBytes) throws -> Data {
        fatalError("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        fatalError("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        fatalError("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureBkndbFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * The main mobile entrypoint for BknDb, thread-safe and exported via UniFFI.
 */
public protocol BknDbEngineProtocol: AnyObject, Sendable {
    
    /**
     * Recursively cascade-deletes `root` and all descendants reachable via `containment_edge`.
     */
    func cascadeDelete(root: UInt64, containmentEdge: String) throws  -> [UInt64]
    
    /**
     * Creates a directed edge between two existing nodes.
     */
    func createEdge(from: UInt64, edgeType: String, to: UInt64, properties: [String: FfiPropValue]) throws  -> UInt64
    
    /**
     * Creates multiple edges in a single atomic transaction.
     */
    func createEdgesBulk(edges: [FfiEdgeInput]) throws  -> [UInt64]
    
    /**
     * Creates a single graph node with the given label and properties.
     */
    func createNode(label: String, properties: [String: FfiPropValue]) throws  -> UInt64
    
    /**
     * Creates multiple nodes in a single atomic transaction.
     */
    func createNodesBulk(nodes: [FfiNodeInput]) throws  -> [UInt64]
    
    /**
     * Deletes a node and all incident edges atomically.
     */
    func deleteNode(id: UInt64) throws 
    
    /**
     * Computes the unweighted shortest path between `start` and `target` using BFS.
     */
    func findShortestPath(start: UInt64, target: UInt64, direction: FfiDirection, edgeTypes: [String]?) throws  -> FfiPathResult?
    
    /**
     * Retrieves an edge by its numeric ID.
     */
    func getEdge(id: UInt64) throws  -> FfiEdgeRecord?
    
    /**
     * Retrieves a node by its numeric ID.
     */
    func getNode(id: UInt64) throws  -> FfiNodeRecord?
    
    /**
     * Returns incoming neighbors for `node` along edges of type `edge_type`.
     */
    func neighborsIn(node: UInt64, edgeType: String) throws  -> [FfiNeighbor]
    
    /**
     * Returns outgoing neighbors for `node` along edges of type `edge_type`.
     */
    func neighborsOut(node: UInt64, edgeType: String) throws  -> [FfiNeighbor]
    
    /**
     * Ingests a structured batch of graph nodes and edges in a single atomic transaction.
     */
    func syncBatch(batch: FfiSyncBatch) throws  -> FfiSyncResult
    
    /**
     * Finds the top `k` hub nodes by degree centrality, optionally filtered by edge type.
     */
    func topHubs(k: UInt32, direction: FfiDirection, edgeType: String?) throws  -> [FfiHubRecord]
    
}
/**
 * The main mobile entrypoint for BknDb, thread-safe and exported via UniFFI.
 */
open class BknDbEngine: BknDbEngineProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_bkndb_ffi_fn_clone_bkndbengine(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_bkndb_ffi_fn_free_bkndbengine(handle, $0) }
    }

    
    /**
     * Creates an ephemeral in-memory database instance.
     */
public static func inMemory()throws  -> BknDbEngine  {
    return try  FfiConverterTypeBknDbEngine_lift(try rustCallWithError(FfiConverterTypeFfiBknError_lift) {
        uniffiCallStatus in
    uniffi_bkndb_ffi_fn_constructor_bkndbengine_in_memory(uniffiCallStatus
    )
})
}
    
    /**
     * Opens or creates an on-disk single-file database at `path`.
     */
public static func `open`(path: String)throws  -> BknDbEngine  {
    return try  FfiConverterTypeBknDbEngine_lift(try rustCallWithError(FfiConverterTypeFfiBknError_lift) {
        uniffiCallStatus in
    uniffi_bkndb_ffi_fn_constructor_bkndbengine_open(
        FfiConverterString.lower(path),uniffiCallStatus
    )
})
}
    

    
    /**
     * Recursively cascade-deletes `root` and all descendants reachable via `containment_edge`.
     */
open func cascadeDelete(root: UInt64, containmentEdge: String)throws  -> [UInt64]  {
    return try  FfiConverterSequenceUInt64.lift(try rustCallWithError(FfiConverterTypeFfiBknError_lift) {
        uniffiCallStatus in
    uniffi_bkndb_ffi_fn_method_bkndbengine_cascade_delete(
            self.uniffiCloneHandle(),
        FfiConverterUInt64.lower(root),
        FfiConverterString.lower(containmentEdge),uniffiCallStatus
    )
})
}
    
    /**
     * Creates a directed edge between two existing nodes.
     */
open func createEdge(from: UInt64, edgeType: String, to: UInt64, properties: [String: FfiPropValue])throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeFfiBknError_lift) {
        uniffiCallStatus in
    uniffi_bkndb_ffi_fn_method_bkndbengine_create_edge(
            self.uniffiCloneHandle(),
        FfiConverterUInt64.lower(from),
        FfiConverterString.lower(edgeType),
        FfiConverterUInt64.lower(to),
        FfiConverterDictionaryStringTypeFfiPropValue.lower(properties),uniffiCallStatus
    )
})
}
    
    /**
     * Creates multiple edges in a single atomic transaction.
     */
open func createEdgesBulk(edges: [FfiEdgeInput])throws  -> [UInt64]  {
    return try  FfiConverterSequenceUInt64.lift(try rustCallWithError(FfiConverterTypeFfiBknError_lift) {
        uniffiCallStatus in
    uniffi_bkndb_ffi_fn_method_bkndbengine_create_edges_bulk(
            self.uniffiCloneHandle(),
        FfiConverterSequenceTypeFfiEdgeInput.lower(edges),uniffiCallStatus
    )
})
}
    
    /**
     * Creates a single graph node with the given label and properties.
     */
open func createNode(label: String, properties: [String: FfiPropValue])throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeFfiBknError_lift) {
        uniffiCallStatus in
    uniffi_bkndb_ffi_fn_method_bkndbengine_create_node(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(label),
        FfiConverterDictionaryStringTypeFfiPropValue.lower(properties),uniffiCallStatus
    )
})
}
    
    /**
     * Creates multiple nodes in a single atomic transaction.
     */
open func createNodesBulk(nodes: [FfiNodeInput])throws  -> [UInt64]  {
    return try  FfiConverterSequenceUInt64.lift(try rustCallWithError(FfiConverterTypeFfiBknError_lift) {
        uniffiCallStatus in
    uniffi_bkndb_ffi_fn_method_bkndbengine_create_nodes_bulk(
            self.uniffiCloneHandle(),
        FfiConverterSequenceTypeFfiNodeInput.lower(nodes),uniffiCallStatus
    )
})
}
    
    /**
     * Deletes a node and all incident edges atomically.
     */
open func deleteNode(id: UInt64)throws   {try rustCallWithError(FfiConverterTypeFfiBknError_lift) {
        uniffiCallStatus in
    uniffi_bkndb_ffi_fn_method_bkndbengine_delete_node(
            self.uniffiCloneHandle(),
        FfiConverterUInt64.lower(id),uniffiCallStatus
    )
}
}
    
    /**
     * Computes the unweighted shortest path between `start` and `target` using BFS.
     */
open func findShortestPath(start: UInt64, target: UInt64, direction: FfiDirection, edgeTypes: [String]?)throws  -> FfiPathResult?  {
    return try  FfiConverterOptionTypeFfiPathResult.lift(try rustCallWithError(FfiConverterTypeFfiBknError_lift) {
        uniffiCallStatus in
    uniffi_bkndb_ffi_fn_method_bkndbengine_find_shortest_path(
            self.uniffiCloneHandle(),
        FfiConverterUInt64.lower(start),
        FfiConverterUInt64.lower(target),
        FfiConverterTypeFfiDirection_lower(direction),
        FfiConverterOptionSequenceString.lower(edgeTypes),uniffiCallStatus
    )
})
}
    
    /**
     * Retrieves an edge by its numeric ID.
     */
open func getEdge(id: UInt64)throws  -> FfiEdgeRecord?  {
    return try  FfiConverterOptionTypeFfiEdgeRecord.lift(try rustCallWithError(FfiConverterTypeFfiBknError_lift) {
        uniffiCallStatus in
    uniffi_bkndb_ffi_fn_method_bkndbengine_get_edge(
            self.uniffiCloneHandle(),
        FfiConverterUInt64.lower(id),uniffiCallStatus
    )
})
}
    
    /**
     * Retrieves a node by its numeric ID.
     */
open func getNode(id: UInt64)throws  -> FfiNodeRecord?  {
    return try  FfiConverterOptionTypeFfiNodeRecord.lift(try rustCallWithError(FfiConverterTypeFfiBknError_lift) {
        uniffiCallStatus in
    uniffi_bkndb_ffi_fn_method_bkndbengine_get_node(
            self.uniffiCloneHandle(),
        FfiConverterUInt64.lower(id),uniffiCallStatus
    )
})
}
    
    /**
     * Returns incoming neighbors for `node` along edges of type `edge_type`.
     */
open func neighborsIn(node: UInt64, edgeType: String)throws  -> [FfiNeighbor]  {
    return try  FfiConverterSequenceTypeFfiNeighbor.lift(try rustCallWithError(FfiConverterTypeFfiBknError_lift) {
        uniffiCallStatus in
    uniffi_bkndb_ffi_fn_method_bkndbengine_neighbors_in(
            self.uniffiCloneHandle(),
        FfiConverterUInt64.lower(node),
        FfiConverterString.lower(edgeType),uniffiCallStatus
    )
})
}
    
    /**
     * Returns outgoing neighbors for `node` along edges of type `edge_type`.
     */
open func neighborsOut(node: UInt64, edgeType: String)throws  -> [FfiNeighbor]  {
    return try  FfiConverterSequenceTypeFfiNeighbor.lift(try rustCallWithError(FfiConverterTypeFfiBknError_lift) {
        uniffiCallStatus in
    uniffi_bkndb_ffi_fn_method_bkndbengine_neighbors_out(
            self.uniffiCloneHandle(),
        FfiConverterUInt64.lower(node),
        FfiConverterString.lower(edgeType),uniffiCallStatus
    )
})
}
    
    /**
     * Ingests a structured batch of graph nodes and edges in a single atomic transaction.
     */
open func syncBatch(batch: FfiSyncBatch)throws  -> FfiSyncResult  {
    return try  FfiConverterTypeFfiSyncResult_lift(try rustCallWithError(FfiConverterTypeFfiBknError_lift) {
        uniffiCallStatus in
    uniffi_bkndb_ffi_fn_method_bkndbengine_sync_batch(
            self.uniffiCloneHandle(),
        FfiConverterTypeFfiSyncBatch_lower(batch),uniffiCallStatus
    )
})
}
    
    /**
     * Finds the top `k` hub nodes by degree centrality, optionally filtered by edge type.
     */
open func topHubs(k: UInt32, direction: FfiDirection, edgeType: String?)throws  -> [FfiHubRecord]  {
    return try  FfiConverterSequenceTypeFfiHubRecord.lift(try rustCallWithError(FfiConverterTypeFfiBknError_lift) {
        uniffiCallStatus in
    uniffi_bkndb_ffi_fn_method_bkndbengine_top_hubs(
            self.uniffiCloneHandle(),
        FfiConverterUInt32.lower(k),
        FfiConverterTypeFfiDirection_lower(direction),
        FfiConverterOptionString.lower(edgeType),uniffiCallStatus
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBknDbEngine: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = BknDbEngine

    public static func lift(_ handle: UInt64) throws -> BknDbEngine {
        return BknDbEngine(unsafeFromHandle: handle)
    }

    public static func lower(_ value: BknDbEngine) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BknDbEngine {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: BknDbEngine, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBknDbEngine_lift(_ handle: UInt64) throws -> BknDbEngine {
    return try FfiConverterTypeBknDbEngine.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBknDbEngine_lower(_ value: BknDbEngine) -> UInt64 {
    return FfiConverterTypeBknDbEngine.lower(value)
}




public struct FfiEdgeInput: Equatable, Hashable {
    public var from: UInt64
    public var edgeType: String
    public var to: UInt64
    public var properties: [String: FfiPropValue]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(from: UInt64, edgeType: String, to: UInt64, properties: [String: FfiPropValue]) {
        self.from = from
        self.edgeType = edgeType
        self.to = to
        self.properties = properties
    }

    

    
}

#if compiler(>=6)
extension FfiEdgeInput: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiEdgeInput: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiEdgeInput {
        return
            try FfiEdgeInput(
                from: FfiConverterUInt64.read(from: &buf), 
                edgeType: FfiConverterString.read(from: &buf), 
                to: FfiConverterUInt64.read(from: &buf), 
                properties: FfiConverterDictionaryStringTypeFfiPropValue.read(from: &buf)
        )
    }

    public static func write(_ value: FfiEdgeInput, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.from, into: &buf)
        FfiConverterString.write(value.edgeType, into: &buf)
        FfiConverterUInt64.write(value.to, into: &buf)
        FfiConverterDictionaryStringTypeFfiPropValue.write(value.properties, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiEdgeInput_lift(_ buf: RustBuffer) throws -> FfiEdgeInput {
    return try FfiConverterTypeFfiEdgeInput.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiEdgeInput_lower(_ value: FfiEdgeInput) -> RustBuffer {
    return FfiConverterTypeFfiEdgeInput.lower(value)
}


public struct FfiEdgeRecord: Equatable, Hashable {
    public var id: UInt64
    public var from: UInt64
    public var to: UInt64
    public var edgeType: String
    public var properties: [String: FfiPropValue]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: UInt64, from: UInt64, to: UInt64, edgeType: String, properties: [String: FfiPropValue]) {
        self.id = id
        self.from = from
        self.to = to
        self.edgeType = edgeType
        self.properties = properties
    }

    

    
}

#if compiler(>=6)
extension FfiEdgeRecord: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiEdgeRecord: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiEdgeRecord {
        return
            try FfiEdgeRecord(
                id: FfiConverterUInt64.read(from: &buf), 
                from: FfiConverterUInt64.read(from: &buf), 
                to: FfiConverterUInt64.read(from: &buf), 
                edgeType: FfiConverterString.read(from: &buf), 
                properties: FfiConverterDictionaryStringTypeFfiPropValue.read(from: &buf)
        )
    }

    public static func write(_ value: FfiEdgeRecord, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.id, into: &buf)
        FfiConverterUInt64.write(value.from, into: &buf)
        FfiConverterUInt64.write(value.to, into: &buf)
        FfiConverterString.write(value.edgeType, into: &buf)
        FfiConverterDictionaryStringTypeFfiPropValue.write(value.properties, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiEdgeRecord_lift(_ buf: RustBuffer) throws -> FfiEdgeRecord {
    return try FfiConverterTypeFfiEdgeRecord.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiEdgeRecord_lower(_ value: FfiEdgeRecord) -> RustBuffer {
    return FfiConverterTypeFfiEdgeRecord.lower(value)
}


public struct FfiHubRecord: Equatable, Hashable {
    public var nodeId: UInt64
    public var degree: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(nodeId: UInt64, degree: UInt64) {
        self.nodeId = nodeId
        self.degree = degree
    }

    

    
}

#if compiler(>=6)
extension FfiHubRecord: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiHubRecord: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiHubRecord {
        return
            try FfiHubRecord(
                nodeId: FfiConverterUInt64.read(from: &buf), 
                degree: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: FfiHubRecord, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.nodeId, into: &buf)
        FfiConverterUInt64.write(value.degree, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiHubRecord_lift(_ buf: RustBuffer) throws -> FfiHubRecord {
    return try FfiConverterTypeFfiHubRecord.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiHubRecord_lower(_ value: FfiHubRecord) -> RustBuffer {
    return FfiConverterTypeFfiHubRecord.lower(value)
}


public struct FfiNeighbor: Equatable, Hashable {
    public var nodeId: UInt64
    public var edgeId: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(nodeId: UInt64, edgeId: UInt64) {
        self.nodeId = nodeId
        self.edgeId = edgeId
    }

    

    
}

#if compiler(>=6)
extension FfiNeighbor: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiNeighbor: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiNeighbor {
        return
            try FfiNeighbor(
                nodeId: FfiConverterUInt64.read(from: &buf), 
                edgeId: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: FfiNeighbor, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.nodeId, into: &buf)
        FfiConverterUInt64.write(value.edgeId, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiNeighbor_lift(_ buf: RustBuffer) throws -> FfiNeighbor {
    return try FfiConverterTypeFfiNeighbor.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiNeighbor_lower(_ value: FfiNeighbor) -> RustBuffer {
    return FfiConverterTypeFfiNeighbor.lower(value)
}


public struct FfiNodeInput: Equatable, Hashable {
    public var label: String
    public var properties: [String: FfiPropValue]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(label: String, properties: [String: FfiPropValue]) {
        self.label = label
        self.properties = properties
    }

    

    
}

#if compiler(>=6)
extension FfiNodeInput: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiNodeInput: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiNodeInput {
        return
            try FfiNodeInput(
                label: FfiConverterString.read(from: &buf), 
                properties: FfiConverterDictionaryStringTypeFfiPropValue.read(from: &buf)
        )
    }

    public static func write(_ value: FfiNodeInput, into buf: inout [UInt8]) {
        FfiConverterString.write(value.label, into: &buf)
        FfiConverterDictionaryStringTypeFfiPropValue.write(value.properties, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiNodeInput_lift(_ buf: RustBuffer) throws -> FfiNodeInput {
    return try FfiConverterTypeFfiNodeInput.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiNodeInput_lower(_ value: FfiNodeInput) -> RustBuffer {
    return FfiConverterTypeFfiNodeInput.lower(value)
}


public struct FfiNodeRecord: Equatable, Hashable {
    public var id: UInt64
    public var label: String
    public var properties: [String: FfiPropValue]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: UInt64, label: String, properties: [String: FfiPropValue]) {
        self.id = id
        self.label = label
        self.properties = properties
    }

    

    
}

#if compiler(>=6)
extension FfiNodeRecord: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiNodeRecord: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiNodeRecord {
        return
            try FfiNodeRecord(
                id: FfiConverterUInt64.read(from: &buf), 
                label: FfiConverterString.read(from: &buf), 
                properties: FfiConverterDictionaryStringTypeFfiPropValue.read(from: &buf)
        )
    }

    public static func write(_ value: FfiNodeRecord, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.id, into: &buf)
        FfiConverterString.write(value.label, into: &buf)
        FfiConverterDictionaryStringTypeFfiPropValue.write(value.properties, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiNodeRecord_lift(_ buf: RustBuffer) throws -> FfiNodeRecord {
    return try FfiConverterTypeFfiNodeRecord.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiNodeRecord_lower(_ value: FfiNodeRecord) -> RustBuffer {
    return FfiConverterTypeFfiNodeRecord.lower(value)
}


public struct FfiPathResult: Equatable, Hashable {
    public var steps: [FfiPathStep]
    public var nodeIds: [UInt64]
    public var edgeIds: [UInt64]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(steps: [FfiPathStep], nodeIds: [UInt64], edgeIds: [UInt64]) {
        self.steps = steps
        self.nodeIds = nodeIds
        self.edgeIds = edgeIds
    }

    

    
}

#if compiler(>=6)
extension FfiPathResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiPathResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiPathResult {
        return
            try FfiPathResult(
                steps: FfiConverterSequenceTypeFfiPathStep.read(from: &buf), 
                nodeIds: FfiConverterSequenceUInt64.read(from: &buf), 
                edgeIds: FfiConverterSequenceUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: FfiPathResult, into buf: inout [UInt8]) {
        FfiConverterSequenceTypeFfiPathStep.write(value.steps, into: &buf)
        FfiConverterSequenceUInt64.write(value.nodeIds, into: &buf)
        FfiConverterSequenceUInt64.write(value.edgeIds, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPathResult_lift(_ buf: RustBuffer) throws -> FfiPathResult {
    return try FfiConverterTypeFfiPathResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPathResult_lower(_ value: FfiPathResult) -> RustBuffer {
    return FfiConverterTypeFfiPathResult.lower(value)
}


public struct FfiPathStep: Equatable, Hashable {
    public var nodeId: UInt64
    public var viaEdgeId: UInt64?
    public var edgeType: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(nodeId: UInt64, viaEdgeId: UInt64?, edgeType: String?) {
        self.nodeId = nodeId
        self.viaEdgeId = viaEdgeId
        self.edgeType = edgeType
    }

    

    
}

#if compiler(>=6)
extension FfiPathStep: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiPathStep: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiPathStep {
        return
            try FfiPathStep(
                nodeId: FfiConverterUInt64.read(from: &buf), 
                viaEdgeId: FfiConverterOptionUInt64.read(from: &buf), 
                edgeType: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiPathStep, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.nodeId, into: &buf)
        FfiConverterOptionUInt64.write(value.viaEdgeId, into: &buf)
        FfiConverterOptionString.write(value.edgeType, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPathStep_lift(_ buf: RustBuffer) throws -> FfiPathStep {
    return try FfiConverterTypeFfiPathStep.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPathStep_lower(_ value: FfiPathStep) -> RustBuffer {
    return FfiConverterTypeFfiPathStep.lower(value)
}


public struct FfiSyncBatch: Equatable, Hashable {
    public var nodes: [FfiNodeInput]
    public var edges: [FfiEdgeInput]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(nodes: [FfiNodeInput], edges: [FfiEdgeInput]) {
        self.nodes = nodes
        self.edges = edges
    }

    

    
}

#if compiler(>=6)
extension FfiSyncBatch: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiSyncBatch: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiSyncBatch {
        return
            try FfiSyncBatch(
                nodes: FfiConverterSequenceTypeFfiNodeInput.read(from: &buf), 
                edges: FfiConverterSequenceTypeFfiEdgeInput.read(from: &buf)
        )
    }

    public static func write(_ value: FfiSyncBatch, into buf: inout [UInt8]) {
        FfiConverterSequenceTypeFfiNodeInput.write(value.nodes, into: &buf)
        FfiConverterSequenceTypeFfiEdgeInput.write(value.edges, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSyncBatch_lift(_ buf: RustBuffer) throws -> FfiSyncBatch {
    return try FfiConverterTypeFfiSyncBatch.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSyncBatch_lower(_ value: FfiSyncBatch) -> RustBuffer {
    return FfiConverterTypeFfiSyncBatch.lower(value)
}


public struct FfiSyncResult: Equatable, Hashable {
    public var nodeIds: [UInt64]
    public var edgeIds: [UInt64]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(nodeIds: [UInt64], edgeIds: [UInt64]) {
        self.nodeIds = nodeIds
        self.edgeIds = edgeIds
    }

    

    
}

#if compiler(>=6)
extension FfiSyncResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiSyncResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiSyncResult {
        return
            try FfiSyncResult(
                nodeIds: FfiConverterSequenceUInt64.read(from: &buf), 
                edgeIds: FfiConverterSequenceUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: FfiSyncResult, into buf: inout [UInt8]) {
        FfiConverterSequenceUInt64.write(value.nodeIds, into: &buf)
        FfiConverterSequenceUInt64.write(value.edgeIds, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSyncResult_lift(_ buf: RustBuffer) throws -> FfiSyncResult {
    return try FfiConverterTypeFfiSyncResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSyncResult_lower(_ value: FfiSyncResult) -> RustBuffer {
    return FfiConverterTypeFfiSyncResult.lower(value)
}


public 
enum FfiBknError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case Backend(message: String
    )
    case TableNotFound(table: String
    )
    case NotFound
    case Encoding(message: String
    )
    case ReservedTableName(table: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension FfiBknError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiBknError: FfiConverterRustBuffer {
    typealias SwiftType = FfiBknError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiBknError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Backend(
            message: try FfiConverterString.read(from: &buf)
            )
        case 2: return .TableNotFound(
            table: try FfiConverterString.read(from: &buf)
            )
        case 3: return .NotFound
        case 4: return .Encoding(
            message: try FfiConverterString.read(from: &buf)
            )
        case 5: return .ReservedTableName(
            table: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiBknError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Backend(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .TableNotFound(table):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(table, into: &buf)
            
        
        case .NotFound:
            writeInt(&buf, Int32(3))
        
        
        case let .Encoding(message):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .ReservedTableName(table):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(table, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiBknError_lift(_ buf: RustBuffer) throws -> FfiBknError {
    return try FfiConverterTypeFfiBknError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiBknError_lower(_ value: FfiBknError) -> RustBuffer {
    return FfiConverterTypeFfiBknError.lower(value)
}



public enum FfiDirection: Equatable, Hashable {
    
    case out
    case `in`
    case both





}

#if compiler(>=6)
extension FfiDirection: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiDirection: FfiConverterRustBuffer {
    typealias SwiftType = FfiDirection

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiDirection {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .out
        
        case 2: return .`in`
        
        case 3: return .both
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiDirection, into buf: inout [UInt8]) {
        switch value {
        
        
        case .out:
            writeInt(&buf, Int32(1))
        
        
        case .`in`:
            writeInt(&buf, Int32(2))
        
        
        case .both:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiDirection_lift(_ buf: RustBuffer) throws -> FfiDirection {
    return try FfiConverterTypeFfiDirection.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiDirection_lower(_ value: FfiDirection) -> RustBuffer {
    return FfiConverterTypeFfiDirection.lower(value)
}




public enum FfiPropValue: Equatable, Hashable {
    
    case null
    case str(String
    )
    case int(Int64
    )
    case float(Double
    )
    case bool(Bool
    )
    case bytes(Data
    )





}

#if compiler(>=6)
extension FfiPropValue: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiPropValue: FfiConverterRustBuffer {
    typealias SwiftType = FfiPropValue

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiPropValue {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .null
        
        case 2: return .str(try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .int(try FfiConverterInt64.read(from: &buf)
        )
        
        case 4: return .float(try FfiConverterDouble.read(from: &buf)
        )
        
        case 5: return .bool(try FfiConverterBool.read(from: &buf)
        )
        
        case 6: return .bytes(try FfiConverterData.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiPropValue, into buf: inout [UInt8]) {
        switch value {
        
        
        case .null:
            writeInt(&buf, Int32(1))
        
        
        case let .str(v1):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .int(v1):
            writeInt(&buf, Int32(3))
            FfiConverterInt64.write(v1, into: &buf)
            
        
        case let .float(v1):
            writeInt(&buf, Int32(4))
            FfiConverterDouble.write(v1, into: &buf)
            
        
        case let .bool(v1):
            writeInt(&buf, Int32(5))
            FfiConverterBool.write(v1, into: &buf)
            
        
        case let .bytes(v1):
            writeInt(&buf, Int32(6))
            FfiConverterData.write(v1, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPropValue_lift(_ buf: RustBuffer) throws -> FfiPropValue {
    return try FfiConverterTypeFfiPropValue.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPropValue_lower(_ value: FfiPropValue) -> RustBuffer {
    return FfiConverterTypeFfiPropValue.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt64: FfiConverterRustBuffer {
    typealias SwiftType = UInt64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeFfiEdgeRecord: FfiConverterRustBuffer {
    typealias SwiftType = FfiEdgeRecord?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeFfiEdgeRecord.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeFfiEdgeRecord.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeFfiNodeRecord: FfiConverterRustBuffer {
    typealias SwiftType = FfiNodeRecord?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeFfiNodeRecord.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeFfiNodeRecord.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeFfiPathResult: FfiConverterRustBuffer {
    typealias SwiftType = FfiPathResult?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeFfiPathResult.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeFfiPathResult.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterSequenceString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterSequenceString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceUInt64: FfiConverterRustBuffer {
    typealias SwiftType = [UInt64]

    public static func write(_ value: [UInt64], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterUInt64.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UInt64] {
        let len: Int32 = try readInt(&buf)
        var seq = [UInt64]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterUInt64.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiEdgeInput: FfiConverterRustBuffer {
    typealias SwiftType = [FfiEdgeInput]

    public static func write(_ value: [FfiEdgeInput], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiEdgeInput.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiEdgeInput] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiEdgeInput]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiEdgeInput.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiHubRecord: FfiConverterRustBuffer {
    typealias SwiftType = [FfiHubRecord]

    public static func write(_ value: [FfiHubRecord], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiHubRecord.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiHubRecord] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiHubRecord]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiHubRecord.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiNeighbor: FfiConverterRustBuffer {
    typealias SwiftType = [FfiNeighbor]

    public static func write(_ value: [FfiNeighbor], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiNeighbor.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiNeighbor] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiNeighbor]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiNeighbor.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiNodeInput: FfiConverterRustBuffer {
    typealias SwiftType = [FfiNodeInput]

    public static func write(_ value: [FfiNodeInput], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiNodeInput.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiNodeInput] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiNodeInput]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiNodeInput.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiPathStep: FfiConverterRustBuffer {
    typealias SwiftType = [FfiPathStep]

    public static func write(_ value: [FfiPathStep], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiPathStep.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiPathStep] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiPathStep]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiPathStep.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDictionaryStringTypeFfiPropValue: FfiConverterRustBuffer {
    public static func write(_ value: [String: FfiPropValue], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for (key, value) in value {
            FfiConverterString.write(key, into: &buf)
            FfiConverterTypeFfiPropValue.write(value, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String: FfiPropValue] {
        let len: Int32 = try readInt(&buf)
        var dict = [String: FfiPropValue]()
        dict.reserveCapacity(Int(len))
        for _ in 0..<len {
            let key = try FfiConverterString.read(from: &buf)
            let value = try FfiConverterTypeFfiPropValue.read(from: &buf)
            dict[key] = value
        }
        return dict
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_bkndb_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_bkndb_ffi_checksum_method_bkndbengine_cascade_delete() != 35560) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bkndb_ffi_checksum_method_bkndbengine_create_edge() != 19597) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bkndb_ffi_checksum_method_bkndbengine_create_edges_bulk() != 46431) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bkndb_ffi_checksum_method_bkndbengine_create_node() != 55339) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bkndb_ffi_checksum_method_bkndbengine_create_nodes_bulk() != 29999) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bkndb_ffi_checksum_method_bkndbengine_delete_node() != 3983) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bkndb_ffi_checksum_method_bkndbengine_find_shortest_path() != 36954) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bkndb_ffi_checksum_method_bkndbengine_get_edge() != 45481) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bkndb_ffi_checksum_method_bkndbengine_get_node() != 2294) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bkndb_ffi_checksum_method_bkndbengine_neighbors_in() != 30079) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bkndb_ffi_checksum_method_bkndbengine_neighbors_out() != 62954) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bkndb_ffi_checksum_method_bkndbengine_sync_batch() != 57500) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bkndb_ffi_checksum_method_bkndbengine_top_hubs() != 19397) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bkndb_ffi_checksum_constructor_bkndbengine_in_memory() != 31228) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bkndb_ffi_checksum_constructor_bkndbengine_open() != 51928) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureBkndbFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all